## Import Lib

In [1]:
import pandas as pd
from datetime import timedelta
import os
import numpy as np

In [2]:
path = r"C:\Users\Akhil\Downloads\project\StockBazaar_raw\stox_con"

os.chdir(path)
print("Current Working Directory:", os.getcwd())

xlsx_files = [f for f in os.listdir(path) if f.endswith('.xlsx')]

if len(xlsx_files) != 3:
    raise ValueError("There should be exactly 3 .xlsx files in the directory.")

Current Working Directory: C:\Users\Akhil\Downloads\project\StockBazaar_raw\stox_con

In [3]:
st_1 = pd.read_excel(xlsx_files[0])
st_2 = pd.read_excel(xlsx_files[1])
st_3 = pd.read_excel(xlsx_files[2])

c:\Users\Akhil\Office\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\Akhil\Office\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\Akhil\Office\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [4]:
concat_df = pd.concat([st_1, st_2, st_3], ignore_index=True)
concat_df = concat_df[concat_df['End of Call code'] != '404 Not Found']
concat_df = concat_df[concat_df['End of Call code'] != 'CAN_NOT_MAKE_CALL']

In [5]:
output_path = r"C:\Users\Akhil\Downloads\project\StockBazaar_raw\S_31_03.csv"
concat_df.to_csv(output_path, index=False)
print(f"CSV saved to: {output_path}")

CSV saved to: C:\Users\Akhil\Downloads\project\StockBazaar_raw\S_31_03.csv

## load csv file

In [6]:
os.chdir(r"C:\Users\Akhil\Downloads\project\StockBazaar_raw")
print("Current Working Directory:", os.getcwd())

Current Working Directory: C:\Users\Akhil\Downloads\project\StockBazaar_raw

In [7]:
stringee = concat_df

In [8]:
uno = pd.read_csv('69ccc54a7223d25913ee0745.csv')

## Check_point_1

In [9]:
print("stringee:", stringee['Start time'].unique()[:5])

stringee: <DatetimeArray>
['2026-04-01 19:14:58.761000', '2026-04-01 19:14:44.654000',
 '2026-04-01 19:13:31.404000', '2026-04-01 19:12:59.968000',
 '2026-04-01 19:11:25.081000']
Length: 5, dtype: datetime64[ns]

In [10]:
stringee

,ID,Customer number,Hotline,Call type,Start time,End time,Queue duration,Answer duration,Account,Hold duration,Contact,Company ID,End of Call code,Call status
0,call-vn-1-9EYTIVYVSP-1772160896305,919652950974,917971538305,Inbound calls,2026-04-01 19:14:58.761,2026-04-01 19:14:58.766,00:00:00,00:00:00,NaN,00:00:00,Contact 919652950974,NaN,USER_END_CALL,Stopped at IVR
1,call-vn-1-9EYTIVYVSP-1772160896290,919652950974,917971538305,Inbound calls,2026-04-01 19:14:44.654,2026-04-01 19:14:44.659,00:00:00,00:00:00,NaN,00:00:00,Contact 919652950974,NaN,USER_END_CALL,Stopped at IVR
2,call-vn-1-9EYTIVYVSP-1772160896189,918340179874,917971538327,Inbound calls,2026-04-01 19:13:31.404,2026-04-01 19:13:31.409,00:00:00,00:00:00,NaN,00:00:00,Contact 918340179874,NaN,USER_END_CALL,Stopped at IVR
3,call-vn-1-9EYTIVYVSP-1772160896136,918340179874,917971538327,Inbound calls,2026-04-01 19:12:59.968,2026-04-01 19:12:59.973,00:00:00,00:00:00,NaN,00:00:00,Contact 918340179874,NaN,USER_END_CALL,Stopped at IVR
4,call-vn-1-9EYTIVYVSP-1772160896019,917014794458,917949152424,Inbound calls,2026-04-01 19:11:25.081,2026-04-01 19:11:25.086,00:00:00,00:00:00,NaN,00:00:00,Contact 917014794458,NaN,USER_END_CALL,Stopped at IVR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4744,call-vn-1-9EYTIVYVSP-1772160429694,+917722910639,+917949152524,Inbound calls,2026-04-01 08:17:52.609,2026-04-01 08:17:52.621,00:00:00,00:00:00,NaN,00:00:00,NaN,NaN,USER_END_CALL,Stopped at IVR
4745,call-vn-1-9EYTIVYVSP-1772160429275,+916301636327,+917949152521,Inbound calls,2026-04-01 07:47:45.984,2026-04-01 07:47:45.994,00:00:00,00:00:00,NaN,00:00:00,Contact 916301636327,NaN,USER_END_CALL,Stopped at IVR
4746,call-vn-1-9EYTIVYVSP-1772160429066,+919263917165,+917949152524,Inbound calls,2026-04-01 07:32:35.642,2026-04-01 07:32:35.651,00:00:00,00:00:00,NaN,00:00:00,Contact 919263917165,NaN,USER_END_CALL,Stopped at IVR
4747,call-vn-1-9EYTIVYVSP-1772160428970,+917722910639,+917949152524,Inbound calls,2026-04-01 07:25:04.553,2026-04-01 07:25:04.564,00:00:00,00:00:00,NaN,00:00:00,NaN,NaN,USER_END_CALL,Stopped at IVR
4748,call-vn-1-9EYTIVYVSP-1772160428831,+918218446548,+917949152524,Inbound calls,2026-04-01 07:14:54.848,2026-04-01 07:14:54.859,00:00:00,00:00:00,NaN,00:00:00,NaN,NaN,USER_END_CALL,Stopped at IVR

In [11]:
uno

,Call Id,Caller Number,Caller Name,Contact List,call Type,Call Date,Call Time,DID,IVR Id,Campaign Id,...,Call Status,Call Status Extra,All connected Agent Info,Agent Id ( CTC-To),Master Number CTC,Insert Notes,CallBack,HangedUp Reason,All not connected Agent Info,Contact Info
0,2mneessi7177496790315245063,9550281930,NaN,NaN,Quick Call,31/Mar/2026,8:08:23 PM,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,Both Answered,NaN,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...
1,2mnef9dcu177496721808918244,8407911030,NaN,NaN,Quick Call,31/Mar/2026,7:56:58 PM,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,Both Answered,NaN,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...
2,2mnel3k39177496714023526526,9313974075,NaN,NaN,Quick Call,31/Mar/2026,7:55:40 PM,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,Cust. Unans - Agent Ans.,NaN,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...
3,2mnelza55177496707186581607,9999020321,NaN,NaN,Quick Call,31/Mar/2026,7:54:32 PM,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,Both Answered,NaN,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...
4,2mneeu2ti177496685367356239,7411691286,NaN,NaN,Quick Call,31/Mar/2026,7:50:54 PM,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,Both Answered,NaN,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,2mne2chg7177493070890992389,9313974075,NaN,NaN,Quick Call,31/Mar/2026,9:48:29 AM,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,Cust. Unans - Agent Ans.,NaN,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...
322,2mnduhmwt177493059943266512,7096223555,NaN,NaN,Quick Call,31/Mar/2026,9:46:39 AM,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,Both Answered,NaN,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...
323,2mne1gz4u177493055426320862,8179309250,NaN,NaN,Quick Call,31/Mar/2026,9:45:54 AM,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,Cust. Unans - Agent Ans.,NaN,#35861 Mayank,35861.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...
324,2mne1gz4u177493054197972960,7096223555,NaN,NaN,Quick Call,31/Mar/2026,9:45:42 AM,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,Cust. Unans - Agent Ans.,NaN,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...
325,2mne1gz4u177493046634130713,7014967130,NaN,NaN,Quick Call,31/Mar/2026,9:44:26 AM,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,Cust. Unans - Agent Ans.,NaN,#35861 Mayank,35861.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...

In [12]:
stringee['Answer duration'] = stringee['Answer duration'].fillna('00:00:00')
stringee['Queue duration'] = stringee['Queue duration'].fillna('00:00:00')
uno['Call Duration'] = uno['Call Duration'].fillna('00:00:00')
uno['Talk Duration'] = uno['Talk Duration'].fillna('00:00:00')

In [13]:
uno['Hold Duration'] = '00:00:00'

In [14]:
uno

,Call Id,Caller Number,Caller Name,Contact List,call Type,Call Date,Call Time,DID,IVR Id,Campaign Id,...,Call Status Extra,All connected Agent Info,Agent Id ( CTC-To),Master Number CTC,Insert Notes,CallBack,HangedUp Reason,All not connected Agent Info,Contact Info,Hold Duration
0,2mneessi7177496790315245063,9550281930,NaN,NaN,Quick Call,31/Mar/2026,8:08:23 PM,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,NaN,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00
1,2mnef9dcu177496721808918244,8407911030,NaN,NaN,Quick Call,31/Mar/2026,7:56:58 PM,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,NaN,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00
2,2mnel3k39177496714023526526,9313974075,NaN,NaN,Quick Call,31/Mar/2026,7:55:40 PM,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,NaN,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00
3,2mnelza55177496707186581607,9999020321,NaN,NaN,Quick Call,31/Mar/2026,7:54:32 PM,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,NaN,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00
4,2mneeu2ti177496685367356239,7411691286,NaN,NaN,Quick Call,31/Mar/2026,7:50:54 PM,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,NaN,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,2mne2chg7177493070890992389,9313974075,NaN,NaN,Quick Call,31/Mar/2026,9:48:29 AM,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,NaN,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00
322,2mnduhmwt177493059943266512,7096223555,NaN,NaN,Quick Call,31/Mar/2026,9:46:39 AM,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,NaN,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00
323,2mne1gz4u177493055426320862,8179309250,NaN,NaN,Quick Call,31/Mar/2026,9:45:54 AM,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,NaN,#35861 Mayank,35861.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00
324,2mne1gz4u177493054197972960,7096223555,NaN,NaN,Quick Call,31/Mar/2026,9:45:42 AM,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,NaN,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00
325,2mne1gz4u177493046634130713,7014967130,NaN,NaN,Quick Call,31/Mar/2026,9:44:26 AM,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,NaN,#35861 Mayank,35861.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00

In [15]:
# Function to convert durations in hh:mm:ss format to timedelta
def duration_to_timedelta(duration):
    hours, minutes, seconds = map(int, duration.split(':'))
    return timedelta(hours=hours, minutes=minutes, seconds=seconds)

# Convert the 'Queue duration' and 'Answer duration' columns to timedelta
stringee['Queue Duration (timedelta)'] = stringee['Queue duration'].apply(duration_to_timedelta)
stringee['Answer Duration (timedelta)'] = stringee['Answer duration'].apply(duration_to_timedelta)
uno['Call Duration'] = uno['Call Duration'].apply(duration_to_timedelta)
uno['Talk Duration'] = uno['Talk Duration'].apply(duration_to_timedelta)
# Calculate the total duration as timedelta
stringee['Total Duration (timedelta)'] = stringee['Queue Duration (timedelta)'] + stringee['Answer Duration (timedelta)']

# Convert the total duration back to hh:mm:ss format (remove "0 days")
stringee['Total Duration'] = stringee['Total Duration (timedelta)'].apply(lambda x: str(x).split(", ")[-1])
uno['Call Duration'] = uno['Call Duration'].apply(lambda x: str(x).split(", ")[-1])
uno['Talk Duration'] = uno['Talk Duration'].apply(lambda x: str(x).split(", ")[-1])
# Drop intermediate timedelta columns if not needed
stringee = stringee.drop(columns=['Queue Duration (timedelta)', 'Answer Duration (timedelta)', 'Total Duration (timedelta)'])

In [16]:
stringee['Answer duration']

0       00:00:00
1       00:00:00
2       00:00:00
3       00:00:00
4       00:00:00
          ...
4744    00:00:00
4745    00:00:00
4746    00:00:00
4747    00:00:00
4748    00:00:00
Name: Answer duration, Length: 4471, dtype: object

In [17]:
uno['Talk Duration'] = uno['Call Duration'].astype(str).str.split(' ').str[-1]

In [18]:
uno[['Talk Duration']]

    Talk Duration
0        00:03:16
1        00:11:09
2        00:00:36
3        00:00:36
4        00:02:49
..            ...
321      00:00:13
322      00:00:33
323      00:00:36
324      00:00:36
325      00:00:13

[326 rows x 1 columns]

## ETL

In [19]:
uno.columns

Index(['Call Id', 'Caller Number', 'Caller Name', 'Contact List', 'call Type',
       'Call Date', 'Call Time', 'DID', 'IVR Id', 'Campaign Id',
       'Connected Agents', 'Master Agent ID', 'Master Agent Name',
       'Call Duration', 'Queue Duration', 'Customer Duration', 'Talk Duration',
       'Agent Duration', 'Total Credits', 'Call Status', 'Call Status Extra',
       'All connected Agent Info', 'Agent Id ( CTC-To)', 'Master Number CTC',
       'Insert Notes', 'CallBack', 'HangedUp Reason',
       'All  not  connected  Agent  Info', 'Contact Info', 'Hold Duration'],
      dtype='object')

In [20]:
stringee

,ID,Customer number,Hotline,Call type,Start time,End time,Queue duration,Answer duration,Account,Hold duration,Contact,Company ID,End of Call code,Call status,Total Duration
0,call-vn-1-9EYTIVYVSP-1772160896305,919652950974,917971538305,Inbound calls,2026-04-01 19:14:58.761,2026-04-01 19:14:58.766,00:00:00,00:00:00,NaN,00:00:00,Contact 919652950974,NaN,USER_END_CALL,Stopped at IVR,0 days 00:00:00
1,call-vn-1-9EYTIVYVSP-1772160896290,919652950974,917971538305,Inbound calls,2026-04-01 19:14:44.654,2026-04-01 19:14:44.659,00:00:00,00:00:00,NaN,00:00:00,Contact 919652950974,NaN,USER_END_CALL,Stopped at IVR,0 days 00:00:00
2,call-vn-1-9EYTIVYVSP-1772160896189,918340179874,917971538327,Inbound calls,2026-04-01 19:13:31.404,2026-04-01 19:13:31.409,00:00:00,00:00:00,NaN,00:00:00,Contact 918340179874,NaN,USER_END_CALL,Stopped at IVR,0 days 00:00:00
3,call-vn-1-9EYTIVYVSP-1772160896136,918340179874,917971538327,Inbound calls,2026-04-01 19:12:59.968,2026-04-01 19:12:59.973,00:00:00,00:00:00,NaN,00:00:00,Contact 918340179874,NaN,USER_END_CALL,Stopped at IVR,0 days 00:00:00
4,call-vn-1-9EYTIVYVSP-1772160896019,917014794458,917949152424,Inbound calls,2026-04-01 19:11:25.081,2026-04-01 19:11:25.086,00:00:00,00:00:00,NaN,00:00:00,Contact 917014794458,NaN,USER_END_CALL,Stopped at IVR,0 days 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4744,call-vn-1-9EYTIVYVSP-1772160429694,+917722910639,+917949152524,Inbound calls,2026-04-01 08:17:52.609,2026-04-01 08:17:52.621,00:00:00,00:00:00,NaN,00:00:00,NaN,NaN,USER_END_CALL,Stopped at IVR,0 days 00:00:00
4745,call-vn-1-9EYTIVYVSP-1772160429275,+916301636327,+917949152521,Inbound calls,2026-04-01 07:47:45.984,2026-04-01 07:47:45.994,00:00:00,00:00:00,NaN,00:00:00,Contact 916301636327,NaN,USER_END_CALL,Stopped at IVR,0 days 00:00:00
4746,call-vn-1-9EYTIVYVSP-1772160429066,+919263917165,+917949152524,Inbound calls,2026-04-01 07:32:35.642,2026-04-01 07:32:35.651,00:00:00,00:00:00,NaN,00:00:00,Contact 919263917165,NaN,USER_END_CALL,Stopped at IVR,0 days 00:00:00
4747,call-vn-1-9EYTIVYVSP-1772160428970,+917722910639,+917949152524,Inbound calls,2026-04-01 07:25:04.553,2026-04-01 07:25:04.564,00:00:00,00:00:00,NaN,00:00:00,NaN,NaN,USER_END_CALL,Stopped at IVR,0 days 00:00:00
4748,call-vn-1-9EYTIVYVSP-1772160428831,+918218446548,+917949152524,Inbound calls,2026-04-01 07:14:54.848,2026-04-01 07:14:54.859,00:00:00,00:00:00,NaN,00:00:00,NaN,NaN,USER_END_CALL,Stopped at IVR,0 days 00:00:00

In [21]:
new_string = stringee[['Start time','Account','Call status','Answer duration','Hold duration','Total Duration','Customer number']]

## string date format

In [22]:
#####check
new_string['Start time'].head()

0   2026-04-01 19:14:58.761
1   2026-04-01 19:14:44.654
2   2026-04-01 19:13:31.404
3   2026-04-01 19:12:59.968
4   2026-04-01 19:11:25.081
Name: Start time, dtype: datetime64[ns]

In [23]:
# Function to fix 'new_string' Date Time format
def fix_string_datetime(date_str):
    try:
        # Parse the date and time, assuming format mm/dd/yyyy hh:mm:ss AM/PM
        parsed_date = pd.to_datetime(date_str, errors='coerce', format='%Y-%m-%d %H:%M:%S.%f')
        return parsed_date
    except Exception as e:
        return pd.NaT  # Return NaT for any unparseable date

# Apply this function to the 'Date and Time' column in 'new_string'
new_string['Start time'] = new_string['Start time'].apply(fix_string_datetime)

# Now format it to yyyy/mm/dd HH:mm:ss
new_string['Start time'] = new_string['Start time'].dt.strftime('%Y/%m/%d %H:%M:%S')

# Check the result
print("String unique date formats after fixing:", new_string['Start time'].head())

String unique date formats after fixing: 0    2026/04/01 19:14:58
1    2026/04/01 19:14:44
2    2026/04/01 19:13:31
3    2026/04/01 19:12:59
4    2026/04/01 19:11:25
Name: Start time, dtype: object

C:\Users\Akhil\AppData\Local\Temp\ipykernel_10448\1218228788.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_string['Start time'] = new_string['Start time'].apply(fix_string_datetime)
C:\Users\Akhil\AppData\Local\Temp\ipykernel_10448\1218228788.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_string['Start time'] = new_string['Start time'].dt.strftime('%Y/%m/%d %H:%M:%S')

In [24]:
# Function to separate Date and Call Start Time
def split_date_time(df, col_name):
    # Convert to datetime first (if not already done)
    df[col_name] = pd.to_datetime(df[col_name], errors='coerce', format='%Y/%m/%d %H:%M:%S')

    # Extract the Date (yyyy/mm/dd) and Time (hh:mm:ss)
    df['Date'] = df[col_name].dt.date
    df['Call Start Time'] = df[col_name].dt.strftime('%H:%M:%S')

    return df

# Apply the function to each dataframe
# new_voiso = split_date_time(new_voiso, 'Date and time')
new_string = split_date_time(new_string, 'Start time')

# Verify the changes
print(new_string[['Date', 'Call Start Time']].head())

         Date Call Start Time
0  2026-04-01        19:14:58
1  2026-04-01        19:14:44
2  2026-04-01        19:13:31
3  2026-04-01        19:12:59
4  2026-04-01        19:11:25

C:\Users\Akhil\AppData\Local\Temp\ipykernel_10448\38602727.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col_name] = pd.to_datetime(df[col_name], errors='coerce', format='%Y/%m/%d %H:%M:%S')
C:\Users\Akhil\AppData\Local\Temp\ipykernel_10448\38602727.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date'] = df[col_name].dt.date
C:\Users\Akhil\AppData\Local\Temp\ipykernel_10448\38602727.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Call Start Time'] = df[col_name].dt.strftime('%H:%M:%S')

In [25]:
uno.rename(columns={'Call Date': 'Date'}, inplace=True)

In [26]:
uno['Call Time'] = pd.to_datetime(
    uno['Call Time'], format='%I:%M:%S %p'
).dt.time
uno['Call Time']

0      20:08:23
1      19:56:58
2      19:55:40
3      19:54:32
4      19:50:54
         ...
321    09:48:29
322    09:46:39
323    09:45:54
324    09:45:42
325    09:44:26
Name: Call Time, Length: 326, dtype: object

### copy of main dfs

In [27]:
string_copy = new_string.copy()

### insert source

In [28]:
string_copy['Source'] = 'Stringee'
uno['Source'] = 'Uno'

In [29]:
uno['Date'] = pd.to_datetime(uno['Date'], format='%d/%b/%Y').dt.date

In [30]:
print(string_copy['Date'].unique())
print(uno['Date'].unique())

[datetime.date(2026, 4, 1)]
[datetime.date(2026, 3, 31)]

### Rename Columns

In [31]:

string_copy.rename(columns={
    'Date': 'Date',    
    'Account': 'Dialer Name',
    'Customer number': 'Number',
    'Call status': 'Call Status',
    'Answer duration': 'Talk Time',
    'Hold duration': 'Hold Time',
    'Total Duration': 'Total Call Duration',
    'Call Start Time': 'Call Start Time'
}, inplace=True)

In [32]:
uno.columns

Index(['Call Id', 'Caller Number', 'Caller Name', 'Contact List', 'call Type',
       'Date', 'Call Time', 'DID', 'IVR Id', 'Campaign Id', 'Connected Agents',
       'Master Agent ID', 'Master Agent Name', 'Call Duration',
       'Queue Duration', 'Customer Duration', 'Talk Duration',
       'Agent Duration', 'Total Credits', 'Call Status', 'Call Status Extra',
       'All connected Agent Info', 'Agent Id ( CTC-To)', 'Master Number CTC',
       'Insert Notes', 'CallBack', 'HangedUp Reason',
       'All  not  connected  Agent  Info', 'Contact Info', 'Hold Duration',
       'Source'],
      dtype='object')

In [33]:
uno.rename(columns={
    'Date': 'Date',
    'Master Agent Name': 'Dialer Name',
    'Caller Number': 'Number',
    'Call Status': 'Call Status',
    'Talk Duration': 'Talk Time',
    'Hold Duration': 'Hold Time',
    'Call Duration': 'Total Call Duration',
    'Call Time': 'Call Start Time'
}, inplace=True)
uno

,Call Id,Number,Caller Name,Contact List,call Type,Date,Call Start Time,DID,IVR Id,Campaign Id,...,All connected Agent Info,Agent Id ( CTC-To),Master Number CTC,Insert Notes,CallBack,HangedUp Reason,All not connected Agent Info,Contact Info,Hold Time,Source
0,2mneessi7177496790315245063,9550281930,NaN,NaN,Quick Call,2026-03-31,20:08:23,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00,Uno
1,2mnef9dcu177496721808918244,8407911030,NaN,NaN,Quick Call,2026-03-31,19:56:58,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00,Uno
2,2mnel3k39177496714023526526,9313974075,NaN,NaN,Quick Call,2026-03-31,19:55:40,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00,Uno
3,2mnelza55177496707186581607,9999020321,NaN,NaN,Quick Call,2026-03-31,19:54:32,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00,Uno
4,2mneeu2ti177496685367356239,7411691286,NaN,NaN,Quick Call,2026-03-31,19:50:54,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00,Uno
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,2mne2chg7177493070890992389,9313974075,NaN,NaN,Quick Call,2026-03-31,09:48:29,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00,Uno
322,2mnduhmwt177493059943266512,7096223555,NaN,NaN,Quick Call,2026-03-31,09:46:39,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00,Uno
323,2mne1gz4u177493055426320862,8179309250,NaN,NaN,Quick Call,2026-03-31,09:45:54,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,#35861 Mayank,35861.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00,Uno
324,2mne1gz4u177493054197972960,7096223555,NaN,NaN,Quick Call,2026-03-31,09:45:42,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00,Uno
325,2mne1gz4u177493046634130713,7014967130,NaN,NaN,Quick Call,2026-03-31,09:44:26,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,#35861 Mayank,35861.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00,Uno

In [34]:
uno.rename(columns={
    'Date': 'Date',
    'Master Agent Name': 'Dialer Name',
    'Caller Number': 'Number',
    'Call Status': 'Call Status',
    'Talk Duration': 'Talk Time',
    'Hold Duration': 'Hold Time',
    'Call Duration': 'Total Call Duration',
    'Call Time': 'Call Start Time'
}, inplace=True)

uno['Call Status'] = uno['Call Status'].apply(
    lambda x: 'Answered' if x == 'Both Answered' else 'Missed'
)
uno

,Call Id,Number,Caller Name,Contact List,call Type,Date,Call Start Time,DID,IVR Id,Campaign Id,...,All connected Agent Info,Agent Id ( CTC-To),Master Number CTC,Insert Notes,CallBack,HangedUp Reason,All not connected Agent Info,Contact Info,Hold Time,Source
0,2mneessi7177496790315245063,9550281930,NaN,NaN,Quick Call,2026-03-31,20:08:23,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00,Uno
1,2mnef9dcu177496721808918244,8407911030,NaN,NaN,Quick Call,2026-03-31,19:56:58,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00,Uno
2,2mnel3k39177496714023526526,9313974075,NaN,NaN,Quick Call,2026-03-31,19:55:40,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00,Uno
3,2mnelza55177496707186581607,9999020321,NaN,NaN,Quick Call,2026-03-31,19:54:32,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00,Uno
4,2mneeu2ti177496685367356239,7411691286,NaN,NaN,Quick Call,2026-03-31,19:50:54,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00,Uno
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,2mne2chg7177493070890992389,9313974075,NaN,NaN,Quick Call,2026-03-31,09:48:29,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00,Uno
322,2mnduhmwt177493059943266512,7096223555,NaN,NaN,Quick Call,2026-03-31,09:46:39,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00,Uno
323,2mne1gz4u177493055426320862,8179309250,NaN,NaN,Quick Call,2026-03-31,09:45:54,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,#35861 Mayank,35861.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00,Uno
324,2mne1gz4u177493054197972960,7096223555,NaN,NaN,Quick Call,2026-03-31,09:45:42,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,#35865 Shaqib,35865.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00,Uno
325,2mne1gz4u177493046634130713,7014967130,NaN,NaN,Quick Call,2026-03-31,09:44:26,NaN,Default Quick Call IVR,Default Quick Call Campaign,...,#35861 Mayank,35861.0,NaN,NaN,NaN,Ivr Flow Finished,NaN,userId : 16489039 | fromType : agent | from : ...,00:00:00,Uno

In [35]:
string_copy

,Start time,Dialer Name,Call Status,Talk Time,Hold Time,Total Call Duration,Number,Date,Call Start Time,Source
0,2026-04-01 19:14:58,NaN,Stopped at IVR,00:00:00,00:00:00,0 days 00:00:00,919652950974,2026-04-01,19:14:58,Stringee
1,2026-04-01 19:14:44,NaN,Stopped at IVR,00:00:00,00:00:00,0 days 00:00:00,919652950974,2026-04-01,19:14:44,Stringee
2,2026-04-01 19:13:31,NaN,Stopped at IVR,00:00:00,00:00:00,0 days 00:00:00,918340179874,2026-04-01,19:13:31,Stringee
3,2026-04-01 19:12:59,NaN,Stopped at IVR,00:00:00,00:00:00,0 days 00:00:00,918340179874,2026-04-01,19:12:59,Stringee
4,2026-04-01 19:11:25,NaN,Stopped at IVR,00:00:00,00:00:00,0 days 00:00:00,917014794458,2026-04-01,19:11:25,Stringee
...,...,...,...,...,...,...,...,...,...,...
4744,2026-04-01 08:17:52,NaN,Stopped at IVR,00:00:00,00:00:00,0 days 00:00:00,+917722910639,2026-04-01,08:17:52,Stringee
4745,2026-04-01 07:47:45,NaN,Stopped at IVR,00:00:00,00:00:00,0 days 00:00:00,+916301636327,2026-04-01,07:47:45,Stringee
4746,2026-04-01 07:32:35,NaN,Stopped at IVR,00:00:00,00:00:00,0 days 00:00:00,+919263917165,2026-04-01,07:32:35,Stringee
4747,2026-04-01 07:25:04,NaN,Stopped at IVR,00:00:00,00:00:00,0 days 00:00:00,+917722910639,2026-04-01,07:25:04,Stringee
4748,2026-04-01 07:14:54,NaN,Stopped at IVR,00:00:00,00:00:00,0 days 00:00:00,+918218446548,2026-04-01,07:14:54,Stringee

In [36]:
print(string_copy.shape)

(4471, 10)

In [37]:
print(string_copy['Date'].unique())

[datetime.date(2026, 4, 1)]

In [38]:
string_copy.shape

(4471, 10)

In [39]:

# Select only the required columns from each dataframe
string_selected = string_copy[['Source','Date', 'Dialer Name','Number', 'Call Status','Call Start Time','Total Call Duration', 'Talk Time', 'Hold Time']]
uno_selected = uno[['Source','Date', 'Dialer Name','Number', 'Call Status','Call Start Time','Total Call Duration', 'Talk Time', 'Hold Time']]

# Now concatenate
combined = pd.concat([string_selected, uno_selected], ignore_index=True)

In [40]:
combined

,Source,Date,Dialer Name,Number,Call Status,Call Start Time,Total Call Duration,Talk Time,Hold Time
0,Stringee,2026-04-01,NaN,919652950974,Stopped at IVR,19:14:58,0 days 00:00:00,00:00:00,00:00:00
1,Stringee,2026-04-01,NaN,919652950974,Stopped at IVR,19:14:44,0 days 00:00:00,00:00:00,00:00:00
2,Stringee,2026-04-01,NaN,918340179874,Stopped at IVR,19:13:31,0 days 00:00:00,00:00:00,00:00:00
3,Stringee,2026-04-01,NaN,918340179874,Stopped at IVR,19:12:59,0 days 00:00:00,00:00:00,00:00:00
4,Stringee,2026-04-01,NaN,917014794458,Stopped at IVR,19:11:25,0 days 00:00:00,00:00:00,00:00:00
...,...,...,...,...,...,...,...,...,...
4792,Uno,2026-03-31,Shaqib,9313974075,Missed,09:48:29,0 days 00:00:13,00:00:13,00:00:00
4793,Uno,2026-03-31,Shaqib,7096223555,Answered,09:46:39,0 days 00:00:33,00:00:33,00:00:00
4794,Uno,2026-03-31,Mayank,8179309250,Missed,09:45:54,0 days 00:00:36,00:00:36,00:00:00
4795,Uno,2026-03-31,Shaqib,7096223555,Missed,09:45:42,0 days 00:00:36,00:00:36,00:00:00
4796,Uno,2026-03-31,Mayank,7014967130,Missed,09:44:26,0 days 00:00:13,00:00:13,00:00:00

In [41]:
combined

,Source,Date,Dialer Name,Number,Call Status,Call Start Time,Total Call Duration,Talk Time,Hold Time
0,Stringee,2026-04-01,NaN,919652950974,Stopped at IVR,19:14:58,0 days 00:00:00,00:00:00,00:00:00
1,Stringee,2026-04-01,NaN,919652950974,Stopped at IVR,19:14:44,0 days 00:00:00,00:00:00,00:00:00
2,Stringee,2026-04-01,NaN,918340179874,Stopped at IVR,19:13:31,0 days 00:00:00,00:00:00,00:00:00
3,Stringee,2026-04-01,NaN,918340179874,Stopped at IVR,19:12:59,0 days 00:00:00,00:00:00,00:00:00
4,Stringee,2026-04-01,NaN,917014794458,Stopped at IVR,19:11:25,0 days 00:00:00,00:00:00,00:00:00
...,...,...,...,...,...,...,...,...,...
4792,Uno,2026-03-31,Shaqib,9313974075,Missed,09:48:29,0 days 00:00:13,00:00:13,00:00:00
4793,Uno,2026-03-31,Shaqib,7096223555,Answered,09:46:39,0 days 00:00:33,00:00:33,00:00:00
4794,Uno,2026-03-31,Mayank,8179309250,Missed,09:45:54,0 days 00:00:36,00:00:36,00:00:00
4795,Uno,2026-03-31,Shaqib,7096223555,Missed,09:45:42,0 days 00:00:36,00:00:36,00:00:00
4796,Uno,2026-03-31,Mayank,7014967130,Missed,09:44:26,0 days 00:00:13,00:00:13,00:00:00

In [42]:
duration_cols = ['Total Call Duration', 'Talk Time', 'Hold Time']

def convert_to_timedelta(x):
    if pd.isna(x):
        return pd.Timedelta(seconds=0)
    # If already Timedelta, return as is
    if isinstance(x, pd.Timedelta):
        return x
    # If string has 'days' like '0 days 00:00:45'
    if 'days' in x:
        return pd.to_timedelta(x)
    # If string is just hh:mm:ss
    try:
        h, m, s = map(int, x.split(':'))
        return pd.Timedelta(hours=h, minutes=m, seconds=s)
    except:
        return pd.Timedelta(seconds=0)

# Apply conversion
for col in duration_cols:
    uno[col] = uno[col].apply(convert_to_timedelta)
    
    # Create display column
    uno[col + '_Display'] = uno[col].apply(
        lambda x: f"{int(x.total_seconds()//3600):02d}:"
                  f"{int((x.total_seconds()%3600)//60):02d}:"
                  f"{int(x.total_seconds()%60):02d}"
    )

In [43]:
combined

,Source,Date,Dialer Name,Number,Call Status,Call Start Time,Total Call Duration,Talk Time,Hold Time
0,Stringee,2026-04-01,NaN,919652950974,Stopped at IVR,19:14:58,0 days 00:00:00,00:00:00,00:00:00
1,Stringee,2026-04-01,NaN,919652950974,Stopped at IVR,19:14:44,0 days 00:00:00,00:00:00,00:00:00
2,Stringee,2026-04-01,NaN,918340179874,Stopped at IVR,19:13:31,0 days 00:00:00,00:00:00,00:00:00
3,Stringee,2026-04-01,NaN,918340179874,Stopped at IVR,19:12:59,0 days 00:00:00,00:00:00,00:00:00
4,Stringee,2026-04-01,NaN,917014794458,Stopped at IVR,19:11:25,0 days 00:00:00,00:00:00,00:00:00
...,...,...,...,...,...,...,...,...,...
4792,Uno,2026-03-31,Shaqib,9313974075,Missed,09:48:29,0 days 00:00:13,00:00:13,00:00:00
4793,Uno,2026-03-31,Shaqib,7096223555,Answered,09:46:39,0 days 00:00:33,00:00:33,00:00:00
4794,Uno,2026-03-31,Mayank,8179309250,Missed,09:45:54,0 days 00:00:36,00:00:36,00:00:00
4795,Uno,2026-03-31,Shaqib,7096223555,Missed,09:45:42,0 days 00:00:36,00:00:36,00:00:00
4796,Uno,2026-03-31,Mayank,7014967130,Missed,09:44:26,0 days 00:00:13,00:00:13,00:00:00

In [44]:
combined

,Source,Date,Dialer Name,Number,Call Status,Call Start Time,Total Call Duration,Talk Time,Hold Time
0,Stringee,2026-04-01,NaN,919652950974,Stopped at IVR,19:14:58,0 days 00:00:00,00:00:00,00:00:00
1,Stringee,2026-04-01,NaN,919652950974,Stopped at IVR,19:14:44,0 days 00:00:00,00:00:00,00:00:00
2,Stringee,2026-04-01,NaN,918340179874,Stopped at IVR,19:13:31,0 days 00:00:00,00:00:00,00:00:00
3,Stringee,2026-04-01,NaN,918340179874,Stopped at IVR,19:12:59,0 days 00:00:00,00:00:00,00:00:00
4,Stringee,2026-04-01,NaN,917014794458,Stopped at IVR,19:11:25,0 days 00:00:00,00:00:00,00:00:00
...,...,...,...,...,...,...,...,...,...
4792,Uno,2026-03-31,Shaqib,9313974075,Missed,09:48:29,0 days 00:00:13,00:00:13,00:00:00
4793,Uno,2026-03-31,Shaqib,7096223555,Answered,09:46:39,0 days 00:00:33,00:00:33,00:00:00
4794,Uno,2026-03-31,Mayank,8179309250,Missed,09:45:54,0 days 00:00:36,00:00:36,00:00:00
4795,Uno,2026-03-31,Shaqib,7096223555,Missed,09:45:42,0 days 00:00:36,00:00:36,00:00:00
4796,Uno,2026-03-31,Mayank,7014967130,Missed,09:44:26,0 days 00:00:13,00:00:13,00:00:00

In [45]:
print(combined.isnull().sum())
print(combined.shape)

Source                   0
Date                     0
Dialer Name            429
Number                   0
Call Status              0
Call Start Time          0
Total Call Duration      0
Talk Time                0
Hold Time                0
dtype: int64
(4797, 9)

## Check_point_2

In [46]:
# Filter rows where Date is null
null_date_entries = combined[combined['Date'].isnull()]

# Display the filtered DataFrame
null_date_entries

Empty DataFrame
Columns: [Source, Date, Dialer Name, Number, Call Status, Call Start Time, Total Call Duration, Talk Time, Hold Time]
Index: []

In [47]:
combined['Date'].unique()

array([datetime.date(2026, 4, 1), datetime.date(2026, 3, 31)],
      dtype=object)

In [48]:
combined_df =combined.copy()

In [49]:
# Refine the regex to only remove unwanted patterns
combined_df['Dialer Name'] = combined_df['Dialer Name'].str.replace(r"\s*\([^)]*\)|@.*|;.*", "", regex=True)

# Fill missing 'Dialer Name' values with their original values if they were numeric
combined_df['Dialer Name'] = combined_df['Dialer Name'].fillna(combined['Dialer Name'])

In [50]:
# Replace NaN in 'Hold time' with '00:00:00'
combined_df['Hold Time'] = combined_df['Hold Time'].fillna('00:00:00')

combined_df

,Source,Date,Dialer Name,Number,Call Status,Call Start Time,Total Call Duration,Talk Time,Hold Time
0,Stringee,2026-04-01,NaN,919652950974,Stopped at IVR,19:14:58,0 days 00:00:00,00:00:00,00:00:00
1,Stringee,2026-04-01,NaN,919652950974,Stopped at IVR,19:14:44,0 days 00:00:00,00:00:00,00:00:00
2,Stringee,2026-04-01,NaN,918340179874,Stopped at IVR,19:13:31,0 days 00:00:00,00:00:00,00:00:00
3,Stringee,2026-04-01,NaN,918340179874,Stopped at IVR,19:12:59,0 days 00:00:00,00:00:00,00:00:00
4,Stringee,2026-04-01,NaN,917014794458,Stopped at IVR,19:11:25,0 days 00:00:00,00:00:00,00:00:00
...,...,...,...,...,...,...,...,...,...
4792,Uno,2026-03-31,Shaqib,9313974075,Missed,09:48:29,0 days 00:00:13,00:00:13,00:00:00
4793,Uno,2026-03-31,Shaqib,7096223555,Answered,09:46:39,0 days 00:00:33,00:00:33,00:00:00
4794,Uno,2026-03-31,Mayank,8179309250,Missed,09:45:54,0 days 00:00:36,00:00:36,00:00:00
4795,Uno,2026-03-31,Shaqib,7096223555,Missed,09:45:42,0 days 00:00:36,00:00:36,00:00:00
4796,Uno,2026-03-31,Mayank,7014967130,Missed,09:44:26,0 days 00:00:13,00:00:13,00:00:00

In [51]:
A = combined_df.copy()

In [52]:
# Remove rows where 'Dialer Name' is null
A1 = A[A['Dialer Name'].notnull()]

# Verify the result
print(f"Number of rows after removing null 'Dialer Name': {len(A1)}")

Number of rows after removing null 'Dialer Name': 4368

In [53]:
A1.describe()

,Source,Date,Dialer Name,Number,Call Status,Call Start Time,Total Call Duration,Talk Time,Hold Time
count,4368,4368,4368,4368,4368,4368,4368,4368,4368
unique,2,2,54,3001,2,4137,374,355,11
top,Stringee,2026-04-01,mujeeb,916299281276,Missed,15:37:55,0 days 00:00:36,00:00:00,00:00:00
freq,4096,4096,238,12,2739,3,121,2583,4354

In [54]:
# Check for null values in the 'Dialer Name' column
null_dialer_name_count = combined_df['Dialer Name'].isnull().sum()

# Print the result
print(f"Number of null values in 'Dialer Name': {null_dialer_name_count}")

Number of null values in 'Dialer Name': 429

In [55]:
A1

,Source,Date,Dialer Name,Number,Call Status,Call Start Time,Total Call Duration,Talk Time,Hold Time
70,Stringee,2026-04-01,rahmatullah,919440187007,Missed,07:58:18,0 days 00:00:42,00:00:00,00:00:00
71,Stringee,2026-04-01,abhishek,919764015063,Answered,07:57:58,0 days 00:00:37,00:00:29,00:00:00
72,Stringee,2026-04-01,aayush,917859841130,Answered,07:57:31,0 days 00:03:38,00:03:27,00:00:00
73,Stringee,2026-04-01,mayank,917461881509,Missed,07:57:22,0 days 00:00:13,00:00:00,00:00:00
76,Stringee,2026-04-01,jaideep,919793469474,Missed,07:56:51,0 days 00:00:26,00:00:00,00:00:00
...,...,...,...,...,...,...,...,...,...
4792,Uno,2026-03-31,Shaqib,9313974075,Missed,09:48:29,0 days 00:00:13,00:00:13,00:00:00
4793,Uno,2026-03-31,Shaqib,7096223555,Answered,09:46:39,0 days 00:00:33,00:00:33,00:00:00
4794,Uno,2026-03-31,Mayank,8179309250,Missed,09:45:54,0 days 00:00:36,00:00:36,00:00:00
4795,Uno,2026-03-31,Shaqib,7096223555,Missed,09:45:42,0 days 00:00:36,00:00:36,00:00:00
4796,Uno,2026-03-31,Mayank,7014967130,Missed,09:44:26,0 days 00:00:13,00:00:13,00:00:00

## Check_point_3

In [56]:
unique_dates_per_source = A1.groupby('Source')['Date'].unique()
print(unique_dates_per_source)

Source
Stringee    [2026-04-01]
Uno         [2026-03-31]
Name: Date, dtype: object

In [57]:
A1

,Source,Date,Dialer Name,Number,Call Status,Call Start Time,Total Call Duration,Talk Time,Hold Time
70,Stringee,2026-04-01,rahmatullah,919440187007,Missed,07:58:18,0 days 00:00:42,00:00:00,00:00:00
71,Stringee,2026-04-01,abhishek,919764015063,Answered,07:57:58,0 days 00:00:37,00:00:29,00:00:00
72,Stringee,2026-04-01,aayush,917859841130,Answered,07:57:31,0 days 00:03:38,00:03:27,00:00:00
73,Stringee,2026-04-01,mayank,917461881509,Missed,07:57:22,0 days 00:00:13,00:00:00,00:00:00
76,Stringee,2026-04-01,jaideep,919793469474,Missed,07:56:51,0 days 00:00:26,00:00:00,00:00:00
...,...,...,...,...,...,...,...,...,...
4792,Uno,2026-03-31,Shaqib,9313974075,Missed,09:48:29,0 days 00:00:13,00:00:13,00:00:00
4793,Uno,2026-03-31,Shaqib,7096223555,Answered,09:46:39,0 days 00:00:33,00:00:33,00:00:00
4794,Uno,2026-03-31,Mayank,8179309250,Missed,09:45:54,0 days 00:00:36,00:00:36,00:00:00
4795,Uno,2026-03-31,Shaqib,7096223555,Missed,09:45:42,0 days 00:00:36,00:00:36,00:00:00
4796,Uno,2026-03-31,Mayank,7014967130,Missed,09:44:26,0 days 00:00:13,00:00:13,00:00:00

In [58]:
import re

def normalize_talk_time(talk_time):
    # If the value is in seconds (only digits), convert it to hh:mm:ss
    if re.match(r"^\d+$", str(talk_time)):
        seconds = int(talk_time)
        hours = seconds // 3600
        minutes = (seconds % 3600) // 60
        seconds = seconds % 60
        return f"{hours:02}:{minutes:02}:{seconds:02}"
    elif re.match(r"^\d+:\d+:\d+$", str(talk_time)):
        parts = talk_time.split(":")
        hours = int(parts[0])
        minutes = int(parts[1])
        seconds = int(parts[2])
        return f"{hours:02}:{minutes:02}:{seconds:02}"
    else:
        # Return the value as-is if it doesn't match expected formats
        return talk_time

# Apply the normalization function to the 'Talk Time' column
A1['Talk Time'] = A1['Talk Time'].apply(normalize_talk_time)

# Apply the normalization function to the 'Total Call Duration' column
A1['Total Call Duration'] = A1['Total Call Duration'].apply(normalize_talk_time)


print(A1[['Talk Time', 'Total Call Duration']].head())

   Talk Time Total Call Duration
70  00:00:00     0 days 00:00:42
71  00:00:29     0 days 00:00:37
72  00:03:27     0 days 00:03:38
73  00:00:00     0 days 00:00:13
76  00:00:00     0 days 00:00:26

C:\Users\Akhil\AppData\Local\Temp\ipykernel_10448\4084048447.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  A1['Talk Time'] = A1['Talk Time'].apply(normalize_talk_time)
C:\Users\Akhil\AppData\Local\Temp\ipykernel_10448\4084048447.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  A1['Total Call Duration'] = A1['Total Call Duration'].apply(normalize_talk_time)

In [59]:
unique_talk_time_formats = A1['Talk Time'].unique()

print(f"Unique formats in 'Talk Time': {unique_talk_time_formats}")

Unique formats in 'Talk Time': ['00:00:00' '00:00:29' '00:03:27' '00:00:16' '00:00:10' '00:00:57'
 '00:01:17' '00:00:15' '00:07:05' '00:02:13' '00:02:52' '00:02:51'
 '00:00:23' '00:00:27' '00:00:59' '00:01:13' '00:00:49' '00:03:25'
 '00:01:10' '00:01:03' '00:00:44' '00:03:45' '00:00:37' '00:01:25'
 '00:02:27' '00:03:18' '00:00:53' '00:00:35' '00:00:25' '00:00:05'
 '00:00:18' '00:06:19' '00:01:14' '00:01:15' '00:03:23' '00:00:03'
 '00:17:46' '00:01:08' '00:01:43' '00:02:00' '00:00:34' '00:00:48'
 '00:00:09' '00:18:07' '00:01:09' '00:00:22' '00:02:56' '00:00:46'
 '00:00:26' '00:00:38' '00:00:21' '00:01:32' '00:19:24' '00:00:11'
 '00:14:11' '00:03:52' '00:00:06' '00:00:43' '00:00:17' '00:03:41'
 '00:06:28' '00:11:12' '00:01:45' '00:00:50' '00:00:12' '00:00:28'
 '00:00:20' '00:02:50' '00:02:08' '00:01:39' '00:15:25' '00:00:33'
 '00:01:12' '00:08:58' '00:07:06' '00:01:50' '00:00:31' '00:00:42'
 '00:02:23' '00:00:14' '00:03:42' '00:00:04' '00:00:07' '00:01:05'
 '00:00:36' '00:00:24' '00:01:35' '00:01:16' '00:02:47' '00:04:49'
 '00:01:11' '00:00:30' '00:02:06' '00:00:52' '00:00:02' '00:00:08'
 '00:03:17' '00:00:40' '00:01:38' '00:01:52' '00:04:23' '00:10:45'
 '00:00:01' '00:02:16' '00:02:35' '00:01:34' '00:02:40' '00:01:29'
 '00:10:32' '00:01:56' '00:00:56' '00:15:10' '00:05:30' '00:01:18'
 '00:12:30' '00:01:40' '00:00:54' '00:01:00' '00:01:04' '00:00:55'
 '00:19:34' '00:02:45' '00:01:41' '00:04:17' '00:05:57' '00:01:36'
 '00:01:06' '00:00:13' '00:02:28' '00:00:47' '00:18:49' '00:00:19'
 '00:03:35' '00:01:22' '00:02:04' '00:04:08' '00:05:47' '00:06:44'
 '00:14:16' '00:04:12' '00:00:32' '00:00:58' '00:02:07' '00:03:09'
 '00:01:26' '00:00:41' '00:09:18' '00:06:29' '00:03:31' '00:09:56'
 '00:01:47' '00:05:22' '00:04:47' '00:04:05' '00:05:03' '00:04:04'
 '00:00:51' '00:01:33' '00:03:54' '00:03:08' '00:01:44' '00:01:01'
 '00:24:55' '00:00:39' '00:03:33' '00:02:17' '00:00:45' '00:06:58'
 '00:05:32' '00:04:43' '00:03:39' '00:04:14' '00:06:03' '00:03:03'
 '00:01:20' '00:04:58' '00:01:07' '00:01:21' '00:09:09' '00:01:59'
 '00:02:01' '00:01:49' '00:03:05' '00:05:19' '00:16:38' '00:01:28'
 '00:06:49' '00:15:28' '00:10:21' '00:01:19' '00:02:25' '00:24:19'
 '00:11:21' '00:06:05' '00:21:19' '00:01:51' '00:03:14' '00:04:20'
 '00:01:23' '00:10:07' '00:03:59' '00:09:25' '00:02:55' '00:06:48'
 '00:02:53' '00:04:57' '00:01:02' '00:08:18' '00:03:02' '00:01:24'
 '00:01:48' '00:09:02' '00:01:46' '00:02:48' '00:05:12' '00:04:16'
 '00:10:31' '00:01:42' '00:06:22' '00:03:20' '00:11:04' '00:01:27'
 '00:04:46' '00:04:03' '00:15:05' '00:03:12' '00:02:58' '00:05:08'
 '00:04:21' '00:07:26' '00:02:49' '00:04:54' '00:02:36' '00:02:03'
 '00:03:56' '00:03:36' '00:05:39' '00:02:18' '00:14:10' '00:14:40'
 '00:02:46' '00:04:25' '00:09:23' '00:05:28' '00:02:19' '00:03:29'
 '00:06:06' '00:02:02' '00:09:49' '00:05:37' '00:04:33' '00:06:46'
 '00:26:31' '00:03:48' '00:09:40' '00:03:06' '00:05:18' '00:11:11'
 '00:04:09' '00:02:05' '00:13:31' '00:11:26' '00:08:54' '00:06:33'
 '00:27:53' '00:02:14' '00:02:20' '00:02:30' '00:03:24' '00:04:45'
 '00:11:59' '00:03:13' '00:01:53' '00:02:29' '00:01:37' '00:11:49'
 '00:05:33' '00:03:11' '00:04:26' '00:01:30' '00:05:21' '00:01:54'
 '00:07:43' '00:02:15' '00:03:22' '00:02:41' '00:04:31' '00:01:31'
 '00:03:15' '00:06:08' '00:04:32' '00:08:52' '00:08:35' '00:15:08'
 '00:27:22' '00:03:07' '00:06:41' '00:02:26' '00:09:24' '00:04:40'
 '00:13:13' '00:03:10' '00:15:46' '00:07:02' '00:20:37' '00:26:30'
 '00:01:55' '00:07:01' '00:03:58' '00:03:04' '00:10:13' '00:01:57'
 '00:21:03' '00:04:56' '00:05:46' '00:09:57' '00:06:43' '00:03:57'
 '00:02:12' '00:06:53' '00:14:15' '00:09:38' '00:04:27' '00:03:46'
 '00:06:07' '00:04:10' '00:06:02' '00:03:01' '00:05:05' '00:02:09'
 '00:07:16' '00:04:30' '00:13:17' '00:03:28' '00:10:03' '00:04:28'
 '00:07:46' '00:02:34' '00:02:10' '00:03:37' '00:03:38' '00:05:43'
 '00:18:18' '00:03:53' '00:03:16' '00:11:09' '00:05:13' '00:02:32'
 '00:04:38' '00:10:00' '00:05:15' '00:03:50' '00:04:13' '00:02:38'
 '00:19:53']

#### Unique call status (AOI)

In [60]:
A1['Call Status'].unique()

array(['Missed', 'Answered'], dtype=object)

In [61]:
A1['Call Status'] = A1['Call Status'].apply(
    lambda x: 'connected' if str(x).lower() == 'answered' else 'not connected'
)

C:\Users\Akhil\AppData\Local\Temp\ipykernel_10448\1189403410.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  A1['Call Status'] = A1['Call Status'].apply(

In [62]:
A1

,Source,Date,Dialer Name,Number,Call Status,Call Start Time,Total Call Duration,Talk Time,Hold Time
70,Stringee,2026-04-01,rahmatullah,919440187007,not connected,07:58:18,0 days 00:00:42,00:00:00,00:00:00
71,Stringee,2026-04-01,abhishek,919764015063,connected,07:57:58,0 days 00:00:37,00:00:29,00:00:00
72,Stringee,2026-04-01,aayush,917859841130,connected,07:57:31,0 days 00:03:38,00:03:27,00:00:00
73,Stringee,2026-04-01,mayank,917461881509,not connected,07:57:22,0 days 00:00:13,00:00:00,00:00:00
76,Stringee,2026-04-01,jaideep,919793469474,not connected,07:56:51,0 days 00:00:26,00:00:00,00:00:00
...,...,...,...,...,...,...,...,...,...
4792,Uno,2026-03-31,Shaqib,9313974075,not connected,09:48:29,0 days 00:00:13,00:00:13,00:00:00
4793,Uno,2026-03-31,Shaqib,7096223555,connected,09:46:39,0 days 00:00:33,00:00:33,00:00:00
4794,Uno,2026-03-31,Mayank,8179309250,not connected,09:45:54,0 days 00:00:36,00:00:36,00:00:00
4795,Uno,2026-03-31,Shaqib,7096223555,not connected,09:45:42,0 days 00:00:36,00:00:36,00:00:00
4796,Uno,2026-03-31,Mayank,7014967130,not connected,09:44:26,0 days 00:00:13,00:00:13,00:00:00

In [63]:
len(A1['Dialer Name'].unique())

54

In [64]:
A1['Dialer Name'].unique()

array(['rahmatullah', 'abhishek', 'aayush', 'mayank', 'jaideep', 'abdul',
       'imran', 'aelina', 'akshay', 'prashant', 'Anita', 'walid', 'naman',
       'swati', 'bikash', 'nafisha', 'samar', 'kartik', 'sandhya',
       'raghav', 'Rahul Nex', 'nirvik', 'mujeeb', 'nikita', 'Akshay',
       'omkar', 'prakash', 'deepak', 'sunita', 'abiral', 'ajit', 'atif',
       'vidhya', 'irfan', 'sabina', 'anushka', 'dhruv', 'junaid',
       'ayushman', 'Karishma', 'ankit', 'harish', 'lakhan', 'rizwana',
       'jaya', 'nazia', 'akhil', 'Shaqib', 'Mayank', 'Advik', 'Nishita',
       'Reyansh', 'Abdul', 'Upasana'], dtype=object)

In [65]:
# Count the occurrences of each unique 'Dialer Name' and sort from highest to lowest
dialer_name_counts = A1['Dialer Name'].value_counts().sort_values(ascending=False)

print(dialer_name_counts)

Dialer Name
mujeeb         238
nikita         195
sunita         181
Shaqib         180
swati          177
samar          163
sandhya        162
abiral         151
nirvik         150
junaid         146
naman          144
Akshay         144
deepak         143
sabina         138
prakash        138
anushka        130
ajit           129
vidhya         124
lakhan         123
jaya           120
rizwana        108
bikash         105
kartik          96
jaideep         95
raghav          90
atif            87
prashant        77
irfan           74
nafisha         72
dhruv           70
ayushman        57
imran           50
Mayank          48
Karishma        47
akhil           45
omkar           44
harish          38
Advik           12
Nishita         11
Upasana         10
aayush           9
Reyansh          8
abdul            5
nazia            5
walid            5
abhishek         5
ankit            4
Anita            3
rahmatullah      3
Rahul Nex        3
aelina           2
akshay           2
mayank           1
Abdul            1
Name: count, dtype: int64

In [66]:

combined_df_1 = A1[~A1['Dialer Name'].isin([None, '---'])]

combined_df_1.reset_index(drop=True, inplace=True)

combined_df_1

,Source,Date,Dialer Name,Number,Call Status,Call Start Time,Total Call Duration,Talk Time,Hold Time
0,Stringee,2026-04-01,rahmatullah,919440187007,not connected,07:58:18,0 days 00:00:42,00:00:00,00:00:00
1,Stringee,2026-04-01,abhishek,919764015063,connected,07:57:58,0 days 00:00:37,00:00:29,00:00:00
2,Stringee,2026-04-01,aayush,917859841130,connected,07:57:31,0 days 00:03:38,00:03:27,00:00:00
3,Stringee,2026-04-01,mayank,917461881509,not connected,07:57:22,0 days 00:00:13,00:00:00,00:00:00
4,Stringee,2026-04-01,jaideep,919793469474,not connected,07:56:51,0 days 00:00:26,00:00:00,00:00:00
...,...,...,...,...,...,...,...,...,...
4363,Uno,2026-03-31,Shaqib,9313974075,not connected,09:48:29,0 days 00:00:13,00:00:13,00:00:00
4364,Uno,2026-03-31,Shaqib,7096223555,connected,09:46:39,0 days 00:00:33,00:00:33,00:00:00
4365,Uno,2026-03-31,Mayank,8179309250,not connected,09:45:54,0 days 00:00:36,00:00:36,00:00:00
4366,Uno,2026-03-31,Shaqib,7096223555,not connected,09:45:42,0 days 00:00:36,00:00:36,00:00:00
4367,Uno,2026-03-31,Mayank,7014967130,not connected,09:44:26,0 days 00:00:13,00:00:13,00:00:00

In [67]:
combined_df_1

,Source,Date,Dialer Name,Number,Call Status,Call Start Time,Total Call Duration,Talk Time,Hold Time
0,Stringee,2026-04-01,rahmatullah,919440187007,not connected,07:58:18,0 days 00:00:42,00:00:00,00:00:00
1,Stringee,2026-04-01,abhishek,919764015063,connected,07:57:58,0 days 00:00:37,00:00:29,00:00:00
2,Stringee,2026-04-01,aayush,917859841130,connected,07:57:31,0 days 00:03:38,00:03:27,00:00:00
3,Stringee,2026-04-01,mayank,917461881509,not connected,07:57:22,0 days 00:00:13,00:00:00,00:00:00
4,Stringee,2026-04-01,jaideep,919793469474,not connected,07:56:51,0 days 00:00:26,00:00:00,00:00:00
...,...,...,...,...,...,...,...,...,...
4363,Uno,2026-03-31,Shaqib,9313974075,not connected,09:48:29,0 days 00:00:13,00:00:13,00:00:00
4364,Uno,2026-03-31,Shaqib,7096223555,connected,09:46:39,0 days 00:00:33,00:00:33,00:00:00
4365,Uno,2026-03-31,Mayank,8179309250,not connected,09:45:54,0 days 00:00:36,00:00:36,00:00:00
4366,Uno,2026-03-31,Shaqib,7096223555,not connected,09:45:42,0 days 00:00:36,00:00:36,00:00:00
4367,Uno,2026-03-31,Mayank,7014967130,not connected,09:44:26,0 days 00:00:13,00:00:13,00:00:00

In [68]:
time_columns = ['Call Start Time', 'Total Call Duration', 'Call Duration', 'Gap Duration', 'Talk Time']  # update with your actual columns

# Keep only columns that exist in the DataFrame
time_columns = [col for col in time_columns if col in combined_df_1.columns]

for col in time_columns:
    combined_df_1[col] = combined_df_1[col].astype(str)                  # Convert to string
    combined_df_1[col] = combined_df_1[col].str.replace('0 days ', '', regex=False)  # Remove '0 days '
    combined_df_1[col] = combined_df_1[col].str.strip()                 # Clean whitespace

In [69]:
combined_df_1

,Source,Date,Dialer Name,Number,Call Status,Call Start Time,Total Call Duration,Talk Time,Hold Time
0,Stringee,2026-04-01,rahmatullah,919440187007,not connected,07:58:18,00:00:42,00:00:00,00:00:00
1,Stringee,2026-04-01,abhishek,919764015063,connected,07:57:58,00:00:37,00:00:29,00:00:00
2,Stringee,2026-04-01,aayush,917859841130,connected,07:57:31,00:03:38,00:03:27,00:00:00
3,Stringee,2026-04-01,mayank,917461881509,not connected,07:57:22,00:00:13,00:00:00,00:00:00
4,Stringee,2026-04-01,jaideep,919793469474,not connected,07:56:51,00:00:26,00:00:00,00:00:00
...,...,...,...,...,...,...,...,...,...
4363,Uno,2026-03-31,Shaqib,9313974075,not connected,09:48:29,00:00:13,00:00:13,00:00:00
4364,Uno,2026-03-31,Shaqib,7096223555,connected,09:46:39,00:00:33,00:00:33,00:00:00
4365,Uno,2026-03-31,Mayank,8179309250,not connected,09:45:54,00:00:36,00:00:36,00:00:00
4366,Uno,2026-03-31,Shaqib,7096223555,not connected,09:45:42,00:00:36,00:00:36,00:00:00
4367,Uno,2026-03-31,Mayank,7014967130,not connected,09:44:26,00:00:13,00:00:13,00:00:00

In [70]:
ref_d = pd.read_csv('Team_StockBazaar.csv')

In [71]:
ref_d.nunique()

Dialer            2
Dialer Name      71
Employee Code    56
Full Name        66
Pool              9
TL                5
Vertical          1
Location          2
Email            65
dtype: int64

In [72]:
ref= ref_d.copy()

In [73]:
ref = ref[~ref['Email'].str.contains('inactive', case=False, na=False)]

In [74]:
ref

,Dialer,Dialer Name,Employee Code,Full Name,Pool,TL,Vertical,Location,Email
0,Stringee,ankit@uplora.live,U-1005,Ankit,RM,Virat,MarketBhai,DXB,ankit@uplora.live
1,Stringee,jaideep@uplora.live,E-1418,Jaideep,RM,Virat,MarketBhai,DXB,jaideep@uplora.live
2,Stringee,rahmatullah@uplora.live,E-1381,Rahmatullah,RM,Virat,MarketBhai,DXB,rahmatullah@uplora.live
3,Stringee,sabina@uplora.live,U-1039,Sabina,RM,Pranil,MarketBhai,DXB,sabina@uplora.live
4,Stringee,abdul@uplora.live,E-1236,Abdul,P1,Sameer,MarketBhai,DXB,abdul@uplora.live
...,...,...,...,...,...,...,...,...,...
67,Stringee,prashant@uplora.live,NaN,Prashant A,Pool 5,Virat,MarketBhai,DXB,prashant@uplora.live
68,Stringee,samrat@uplora.live,NaN,Samrat A,Pool 5,Virat,MarketBhai,DXB,samrat@uplora.live
69,Stringee,vidhya@uplora.live,NaN,Vidhya A,Pool 5,Virat,MarketBhai,DXB,vidhya@uplora.live
70,Uno,Aarzoo,NaN,Aarzoo,Pool 5,Virat,MarketBhai,DXB,NaN
71,Uno,Disha,NaN,Disha,Pool 5,Virat,MarketBhai,DXB,disha@uplora.live

## Checkpoint_4

In [75]:
ref.nunique()

Dialer            2
Dialer Name      71
Employee Code    56
Full Name        66
Pool              9
TL                5
Vertical          1
Location          2
Email            65
dtype: int64

In [76]:
for df in [ref, combined_df_1]:
    df['Dialer Name'] = (
        df['Dialer Name']
        .astype(str)  # Convert all values to strings
        .str.replace(r'\s+', ' ', regex=True)  # Replace multiple spaces with a single space
        .str.strip()  # Remove leading and trailing spaces
        .str.replace(r'@.*', '', regex=True)  # Remove everything from and after '@'
        .str.replace(r'\(.*', '', regex=True)  # Remove everything from and after '('
        .str.strip()  # Remove any trailing spaces left after replacements
        .str.lower()  # Convert all text to lowercase
    )

In [77]:
ref.shape

(72, 9)

In [78]:
ref.isnull().sum()

Dialer            0
Dialer Name       0
Employee Code    11
Full Name         0
Pool              0
TL                0
Vertical          0
Location          0
Email             1
dtype: int64

In [79]:
dup = ref[ref.duplicated(subset=['Dialer Name','Email','Dialer'], keep=False)]
dup

Empty DataFrame
Columns: [Dialer, Dialer Name, Employee Code, Full Name, Pool, TL, Vertical, Location, Email]
Index: []

In [80]:
ref = ref.drop_duplicates(subset=['Dialer Name','Email','Dialer'])

In [81]:
ref.rename(columns={'Email': 'CRM ID'}, inplace=True)

In [82]:
ref

,Dialer,Dialer Name,Employee Code,Full Name,Pool,TL,Vertical,Location,CRM ID
0,Stringee,ankit,U-1005,Ankit,RM,Virat,MarketBhai,DXB,ankit@uplora.live
1,Stringee,jaideep,E-1418,Jaideep,RM,Virat,MarketBhai,DXB,jaideep@uplora.live
2,Stringee,rahmatullah,E-1381,Rahmatullah,RM,Virat,MarketBhai,DXB,rahmatullah@uplora.live
3,Stringee,sabina,U-1039,Sabina,RM,Pranil,MarketBhai,DXB,sabina@uplora.live
4,Stringee,abdul,E-1236,Abdul,P1,Sameer,MarketBhai,DXB,abdul@uplora.live
...,...,...,...,...,...,...,...,...,...
67,Stringee,prashant,NaN,Prashant A,Pool 5,Virat,MarketBhai,DXB,prashant@uplora.live
68,Stringee,samrat,NaN,Samrat A,Pool 5,Virat,MarketBhai,DXB,samrat@uplora.live
69,Stringee,vidhya,NaN,Vidhya A,Pool 5,Virat,MarketBhai,DXB,vidhya@uplora.live
70,Uno,aarzoo,NaN,Aarzoo,Pool 5,Virat,MarketBhai,DXB,NaN
71,Uno,disha,NaN,Disha,Pool 5,Virat,MarketBhai,DXB,disha@uplora.live

In [83]:
# Ensure 'Dialer Name' in both dataframes is treated as a string
combined_df_1['Dialer Name'] = combined_df_1['Dialer Name'].astype(str)
ref['Dialer Name'] = ref['Dialer Name'].astype(str)

# Merge the dataframes on 'Dialer Name'
combined_df_2 = combined_df_1.merge(ref, how='left', left_on='Dialer Name', right_on='Dialer Name')


combined_df_2

,Source,Date,Dialer Name,Number,Call Status,Call Start Time,Total Call Duration,Talk Time,Hold Time,Dialer,Employee Code,Full Name,Pool,TL,Vertical,Location,CRM ID
0,Stringee,2026-04-01,rahmatullah,919440187007,not connected,07:58:18,00:00:42,00:00:00,00:00:00,Stringee,E-1381,Rahmatullah,RM,Virat,MarketBhai,DXB,rahmatullah@uplora.live
1,Stringee,2026-04-01,abhishek,919764015063,connected,07:57:58,00:00:37,00:00:29,00:00:00,Stringee,NaN,Abhishek A,Pool 5,Virat,MarketBhai,DXB,abhishek@uplora.live
2,Stringee,2026-04-01,aayush,917859841130,connected,07:57:31,00:03:38,00:03:27,00:00:00,Stringee,U-1124,Aayush,Dialer,KASIF,MarketBhai,IND,aayush@uplora.live
3,Stringee,2026-04-01,mayank,917461881509,not connected,07:57:22,00:00:13,00:00:00,00:00:00,Stringee,U-1009,Mayank,P1,Sameer,MarketBhai,IND,mayank@uplora.live
4,Stringee,2026-04-01,mayank,917461881509,not connected,07:57:22,00:00:13,00:00:00,00:00:00,Uno,U-1009,Mayank,P1,Sameer,MarketBhai,IND,mayank@uplora.live
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4732,Uno,2026-03-31,mayank,8179309250,not connected,09:45:54,00:00:36,00:00:36,00:00:00,Uno,U-1009,Mayank,P1,Sameer,MarketBhai,IND,mayank@uplora.live
4733,Uno,2026-03-31,shaqib,7096223555,not connected,09:45:42,00:00:36,00:00:36,00:00:00,Stringee,E-1232,Shaqib,P1,Sameer,MarketBhai,DXB,shaqib@uplora.live
4734,Uno,2026-03-31,shaqib,7096223555,not connected,09:45:42,00:00:36,00:00:36,00:00:00,Uno,E-1232,Shaqib,P1,Sameer,MarketBhai,DXB,shaqib@uplora.live
4735,Uno,2026-03-31,mayank,7014967130,not connected,09:44:26,00:00:13,00:00:13,00:00:00,Stringee,U-1009,Mayank,P1,Sameer,MarketBhai,IND,mayank@uplora.live
4736,Uno,2026-03-31,mayank,7014967130,not connected,09:44:26,00:00:13,00:00:13,00:00:00,Uno,U-1009,Mayank,P1,Sameer,MarketBhai,IND,mayank@uplora.live

In [84]:
# Filter rows where 'CRM ID' is null
crm_id_null_df = combined_df_2[combined_df_2['CRM ID'].isnull()]

In [85]:

crm_id_null_df['Dialer Name'].unique()

array(['walid', 'nafisha', 'rahul nex', 'nazia'], dtype=object)

## check_point_5

In [86]:
source = crm_id_null_df.groupby('Source')['Dialer Name'].unique()
source

Source
Stringee    [walid, nafisha, rahul nex, nazia]
Name: Dialer Name, dtype: object

In [87]:
crm_id_null_df.shape

(85, 17)

## Raw data

In [88]:
combined_df_2

,Source,Date,Dialer Name,Number,Call Status,Call Start Time,Total Call Duration,Talk Time,Hold Time,Dialer,Employee Code,Full Name,Pool,TL,Vertical,Location,CRM ID
0,Stringee,2026-04-01,rahmatullah,919440187007,not connected,07:58:18,00:00:42,00:00:00,00:00:00,Stringee,E-1381,Rahmatullah,RM,Virat,MarketBhai,DXB,rahmatullah@uplora.live
1,Stringee,2026-04-01,abhishek,919764015063,connected,07:57:58,00:00:37,00:00:29,00:00:00,Stringee,NaN,Abhishek A,Pool 5,Virat,MarketBhai,DXB,abhishek@uplora.live
2,Stringee,2026-04-01,aayush,917859841130,connected,07:57:31,00:03:38,00:03:27,00:00:00,Stringee,U-1124,Aayush,Dialer,KASIF,MarketBhai,IND,aayush@uplora.live
3,Stringee,2026-04-01,mayank,917461881509,not connected,07:57:22,00:00:13,00:00:00,00:00:00,Stringee,U-1009,Mayank,P1,Sameer,MarketBhai,IND,mayank@uplora.live
4,Stringee,2026-04-01,mayank,917461881509,not connected,07:57:22,00:00:13,00:00:00,00:00:00,Uno,U-1009,Mayank,P1,Sameer,MarketBhai,IND,mayank@uplora.live
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4732,Uno,2026-03-31,mayank,8179309250,not connected,09:45:54,00:00:36,00:00:36,00:00:00,Uno,U-1009,Mayank,P1,Sameer,MarketBhai,IND,mayank@uplora.live
4733,Uno,2026-03-31,shaqib,7096223555,not connected,09:45:42,00:00:36,00:00:36,00:00:00,Stringee,E-1232,Shaqib,P1,Sameer,MarketBhai,DXB,shaqib@uplora.live
4734,Uno,2026-03-31,shaqib,7096223555,not connected,09:45:42,00:00:36,00:00:36,00:00:00,Uno,E-1232,Shaqib,P1,Sameer,MarketBhai,DXB,shaqib@uplora.live
4735,Uno,2026-03-31,mayank,7014967130,not connected,09:44:26,00:00:13,00:00:13,00:00:00,Stringee,U-1009,Mayank,P1,Sameer,MarketBhai,IND,mayank@uplora.live
4736,Uno,2026-03-31,mayank,7014967130,not connected,09:44:26,00:00:13,00:00:13,00:00:00,Uno,U-1009,Mayank,P1,Sameer,MarketBhai,IND,mayank@uplora.live

In [89]:
Dialers = combined_df_2[combined_df_2['CRM ID'].notnull() & combined_df_2['Talk Time'].notnull()].copy()

In [90]:
Dialers.isnull().sum()

Source                   0
Date                     0
Dialer Name              0
Number                   0
Call Status              0
Call Start Time          0
Total Call Duration      0
Talk Time                0
Hold Time                0
Dialer                   0
Employee Code          746
Full Name                0
Pool                     0
TL                       0
Vertical                 0
Location                 0
CRM ID                   0
dtype: int64

In [91]:
Dialers = Dialers.drop_duplicates(subset=['Number','Call Start Time'])

In [92]:
XXX = combined_df_2[combined_df_2['Date'].isnull()]
XXX

Empty DataFrame
Columns: [Source, Date, Dialer Name, Number, Call Status, Call Start Time, Total Call Duration, Talk Time, Hold Time, Dialer, Employee Code, Full Name, Pool, TL, Vertical, Location, CRM ID]
Index: []

In [93]:
Dialers.dtypes

Source                 object
Date                   object
Dialer Name            object
Number                 object
Call Status            object
Call Start Time        object
Total Call Duration    object
Talk Time              object
Hold Time              object
Dialer                 object
Employee Code          object
Full Name              object
Pool                   object
TL                     object
Vertical               object
Location               object
CRM ID                 object
dtype: object

In [94]:
# Check Call Start Time type
print(Dialers['Call Start Time'].apply(type).value_counts())

# Check Total Call Duration type
print(Dialers['Total Call Duration'].apply(type).value_counts())

Call Start Time
<class 'str'>    4283
Name: count, dtype: int64
Total Call Duration
<class 'str'>    4283
Name: count, dtype: int64

In [95]:
from datetime import timedelta

Dialers['Date'] = pd.to_datetime(Dialers['Date'], format='%Y-%m-%d', errors='coerce')
Dialers['Call Start Time'] = pd.to_datetime(
    Dialers['Date'].dt.strftime('%Y-%m-%d').fillna('1900-01-01') + ' ' + Dialers['Call Start Time'],
    format='%Y-%m-%d %H:%M:%S',
    errors='coerce'
)

# Convert durations
Dialers['Total Call Duration'] = Dialers['Total Call Duration'].apply(
    lambda x: pd.to_timedelta(x) if isinstance(x, str) else pd.Timedelta(0)
)

# Sort
Dialers = Dialers.sort_values(by=['Date', 'CRM ID', 'Call Start Time']).reset_index(drop=True)

# Init columns
Dialers['Call Gap'] = 'No'
Dialers['Gap Duration'] = '00:00:00'

# Define working hours
start_time = pd.to_datetime('09:30:00').time()
end_time = pd.to_datetime('18:30:00').time()

# Loop through to calculate gaps
for i in range(1, len(Dialers)):
    same_crm = Dialers.loc[i, 'CRM ID'] == Dialers.loc[i - 1, 'CRM ID']
    same_date = Dialers.loc[i, 'Date'] == Dialers.loc[i - 1, 'Date']  

    if same_crm and same_date:
        current_time = Dialers.loc[i, 'Call Start Time'].time()
        previous_time = Dialers.loc[i - 1, 'Call Start Time'].time()

        previous_end = Dialers.loc[i - 1, 'Call Start Time'] + Dialers.loc[i - 1, 'Total Call Duration']
        gap_duration = Dialers.loc[i, 'Call Start Time'] - previous_end

        if gap_duration.total_seconds() < 0:
            gap_duration = timedelta(0)

        # Store formatted gap
        total_seconds = int(gap_duration.total_seconds())
        hours = total_seconds // 3600
        minutes = (total_seconds % 3600) // 60
        seconds = total_seconds % 60
        Dialers.loc[i, 'Gap Duration'] = f"{hours:02}:{minutes:02}:{seconds:02}"

        # Set 'Call Gap' only if within working hours
        if start_time <= current_time <= end_time and start_time <= previous_time <= end_time:
            Dialers.loc[i, 'Call Gap'] = 'Yes' if gap_duration > timedelta(minutes=1) else 'No'

Dialers

,Source,Date,Dialer Name,Number,Call Status,Call Start Time,Total Call Duration,Talk Time,Hold Time,Dialer,Employee Code,Full Name,Pool,TL,Vertical,Location,CRM ID,Call Gap,Gap Duration
0,Uno,2026-03-31,aayush,9892977091,not connected,2026-03-31 11:37:42,0 days 00:00:36,00:00:36,00:00:00,Stringee,U-1124,Aayush,Dialer,KASIF,MarketBhai,IND,aayush@uplora.live,No,00:00:00
1,Uno,2026-03-31,aayush,9892977091,not connected,2026-03-31 11:39:15,0 days 00:00:33,00:00:33,00:00:00,Stringee,U-1124,Aayush,Dialer,KASIF,MarketBhai,IND,aayush@uplora.live,No,00:00:57
2,Uno,2026-03-31,abdul,9079131246,connected,2026-03-31 12:16:52,0 days 00:10:00,00:10:00,00:00:00,Stringee,E-1236,Abdul,P1,Sameer,MarketBhai,DXB,abdul@uplora.live,No,00:00:00
3,Uno,2026-03-31,advik,9194259045,not connected,2026-03-31 13:08:01,0 days 00:00:21,00:00:21,00:00:00,Stringee,U-1130,Advik,Dialer,KASIF,MarketBhai,IND,advik@uplora.live,No,00:00:00
4,Uno,2026-03-31,advik,9425904504,not connected,2026-03-31 13:09:13,0 days 00:00:37,00:00:37,00:00:00,Stringee,U-1130,Advik,Dialer,KASIF,MarketBhai,IND,advik@uplora.live,No,00:00:51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4278,Stringee,2026-04-01,vidhya,918445530137,connected,2026-04-01 18:24:51,0 days 00:00:44,00:00:36,00:00:00,Stringee,NaN,Vidhya A,Pool 5,Virat,MarketBhai,DXB,vidhya@uplora.live,Yes,00:01:04
4279,Stringee,2026-04-01,vidhya,918445530137,connected,2026-04-01 18:25:40,0 days 00:01:11,00:01:05,00:00:00,Stringee,NaN,Vidhya A,Pool 5,Virat,MarketBhai,DXB,vidhya@uplora.live,No,00:00:05
4280,Stringee,2026-04-01,vidhya,919205330143,connected,2026-04-01 18:27:18,0 days 00:00:25,00:00:04,00:00:00,Stringee,NaN,Vidhya A,Pool 5,Virat,MarketBhai,DXB,vidhya@uplora.live,No,00:00:27
4281,Stringee,2026-04-01,vidhya,919205330143,connected,2026-04-01 18:27:57,0 days 00:01:07,00:00:42,00:00:00,Stringee,NaN,Vidhya A,Pool 5,Virat,MarketBhai,DXB,vidhya@uplora.live,No,00:00:14
4282,Stringee,2026-04-01,vidhya,916299281276,not connected,2026-04-01 18:32:30,0 days 00:00:11,00:00:00,00:00:00,Stringee,NaN,Vidhya A,Pool 5,Virat,MarketBhai,DXB,vidhya@uplora.live,No,00:03:26

In [96]:
import re
invalid_values = []

# Function to convert mixed formats to seconds
def to_seconds(value):
    try:
        if isinstance(value, pd.Timedelta):
            return int(value.total_seconds())  # Convert timedelta to seconds
        elif re.match(r"^\d{1,2}:\d{1,2}:\d{1,2}$", str(value)):
            parts = list(map(int, value.split(':')))
            while len(parts) < 3:
                parts.insert(0, 0)  
            return parts[0] * 3600 + parts[1] * 60 + parts[2]
        elif str(value).isdigit():
            return int(value)
        else:
            invalid_values.append(value)
            return value
    except Exception:
        invalid_values.append(value)
        return value

# Replace missing values with empty strings
Dialers['Talk Time'] = Dialers['Talk Time'].fillna('')
Dialers['Hold Time'] = Dialers['Hold Time'].fillna('')
Dialers['Total Call Duration'] = Dialers['Total Call Duration'].fillna('')
Dialers['Gap Duration'] = Dialers['Gap Duration'].fillna('')

# Convert Talk Time, Hold Time, and Total Call Duration to seconds
Dialers['Talk Time (seconds)'] = Dialers['Talk Time'].apply(to_seconds)
Dialers['Hold Time (seconds)'] = Dialers['Hold Time'].apply(to_seconds)
Dialers['Total Duration (seconds)'] = Dialers['Total Call Duration'].apply(to_seconds)
Dialers['Gap Duration (seconds)'] = Dialers['Gap Duration'].apply(to_seconds)

# Notify invalid values
if invalid_values:
    print("Invalid values found in 'Talk Time', 'Total Call Duration', or 'Hold Time':, or 'Call Gap Duration':")
    print(invalid_values)

In [97]:
Dialers.isnull().sum()

Source                        0
Date                          0
Dialer Name                   0
Number                        0
Call Status                   0
Call Start Time               0
Total Call Duration           0
Talk Time                     0
Hold Time                     0
Dialer                        0
Employee Code               616
Full Name                     0
Pool                          0
TL                            0
Vertical                      0
Location                      0
CRM ID                        0
Call Gap                      0
Gap Duration                  0
Talk Time (seconds)           0
Hold Time (seconds)           0
Total Duration (seconds)      0
Gap Duration (seconds)        0
dtype: int64

In [98]:
# Group by 'CRM ID' and 'Date' and calculate 
A = Dialers.groupby(['CRM ID', 'Date']).agg(
    Total_Dialed_Calls=('Call Status', 'count'),
    Unique_Dialed_Numbers=('Number', 'nunique'),
    Total_Connected_Calls=('Call Status', lambda x: (x == 'connected').sum()),
    Total_Number_of_Call_Gap=('Call Gap', lambda x: (x == 'Yes').sum()),
    Total_Call_GT_30=('Talk Time (seconds)', lambda x: ((Dialers.loc[x.index, 'Call Status'] == 'connected') & (x > 30)).sum()),
    Total_Duration=('Total Duration (seconds)', 'sum'),
    Total_Talk_Time=('Talk Time (seconds)', lambda x: x[Dialers.loc[x.index, 'Call Status'] == 'connected'].sum()),
    Total_Talk_Time_GT_30=('Talk Time (seconds)', lambda x: x[(Dialers.loc[x.index, 'Call Status'] == 'connected') & (x > 30)].sum()),
    Total_Connected_Hold_Time=('Hold Time (seconds)', lambda x: x[Dialers.loc[x.index, 'Call Status'] == 'connected'].sum()), 
    Total_Gap_Duration=('Gap Duration (seconds)', 'sum')
).reset_index()

# Fix: Subtract 1hr only if greater, else keep the original value
A['Total_Gap_Duration'] = A['Total_Gap_Duration'].apply(lambda x: x - 3600 if x > 3600 else x)


A['Avg_Gap_per_call'] = A['Total_Gap_Duration'] / A['Total_Dialed_Calls']

# New: Gap Duration After Leverage (give 45 seconds per call, subtract from actual gap used, add to 0 if negative)
A['Gap Duration After Leverage'] = (A['Total_Gap_Duration'] - (A['Total_Dialed_Calls'] * 45)).clip(lower=0)

# Recalculate Login Hours after updated gap
A['Login Hours'] = A['Total_Duration'] + A['Total_Gap_Duration'] + 3600
A['Login Hours'] = pd.to_timedelta(A['Login Hours'], unit='s')
A['Login Hours'] = A['Login Hours'].apply(lambda x: str(x).split()[-1])

# Convert 'Login Hours' string (hh:mm:ss) to timedelta
A['Login Hours (Timedelta)'] = pd.to_timedelta(A['Login Hours'])

# Defining attendance logic
def mark_attendance(td):
    if td < pd.Timedelta(hours=4, minutes=30):
        return 'Absent'
    elif td < pd.Timedelta(hours=6):
        return 'Half Day'
    elif td < pd.Timedelta(hours=8, minutes=30):
        return 'Warning'
    else:
        return 'Present'


A['Attendance'] = A['Login Hours (Timedelta)'].apply(mark_attendance)


A.drop(columns='Login Hours (Timedelta)', inplace=True)


A

,CRM ID,Date,Total_Dialed_Calls,Unique_Dialed_Numbers,Total_Connected_Calls,Total_Number_of_Call_Gap,Total_Call_GT_30,Total_Duration,Total_Talk_Time,Total_Talk_Time_GT_30,Total_Connected_Hold_Time,Total_Gap_Duration,Avg_Gap_per_call,Gap Duration After Leverage,Login Hours,Attendance
0,aayush@uplora.live,2026-03-31,2,1,0,0,0,69,0,0,0,57,28.500000,0,01:02:06,Absent
1,aayush@uplora.live,2026-04-01,7,7,2,0,1,514,217,207,0,1272,181.714286,957,01:29:46,Absent
2,abdul@uplora.live,2026-03-31,1,1,1,0,1,600,600,600,0,0,0.000000,0,01:10:00,Absent
3,abdul@uplora.live,2026-04-01,5,2,1,0,1,284,77,77,0,172,34.400000,0,01:07:36,Absent
4,abhishek@uplora.live,2026-04-01,5,5,2,0,0,168,45,0,0,171,34.200000,0,01:05:39,Absent
5,abiral@uplora.live,2026-04-01,151,62,52,42,28,10099,6347,6004,0,10824,71.682119,4029,06:48:43,Warning
6,advik@uplora.live,2026-03-31,12,11,5,9,4,556,336,307,0,890,74.166667,350,01:24:06,Absent
7,aelina@uplora.live,2026-04-01,2,2,1,0,1,493,425,425,0,437,218.500000,347,01:15:30,Absent
8,ajit@uplora.live,2026-04-01,129,86,53,61,39,11334,7963,7790,7,17472,135.441860,11667,09:00:06,Present
9,akhil@uplora.live,2026-04-01,45,17,3,16,1,1372,441,413,0,4282,95.155556,2257,02:34:14,Absent
10,akshay@uplora.live,2026-04-01,146,121,63,101,30,9022,5134,4648,0,28756,196.958904,22186,11:29:38,Present
11,anita@uplora.live,2026-04-01,3,1,2,0,2,194,119,119,0,129,43.000000,0,01:05:23,Absent
12,ankit@uplora.live,2026-04-01,4,3,2,2,2,1196,1097,1097,0,22274,5568.500000,22094,07:31:10,Warning
13,anushka@uplora.live,2026-04-01,130,87,71,89,43,7892,4746,4281,2,20304,156.184615,14454,08:49:56,Present
14,atif@uplora.live,2026-04-01,87,52,27,43,23,5418,3212,3146,0,10916,125.471264,7001,05:32:14,Half Day
15,ayushman@uplora.live,2026-04-01,57,46,19,22,13,5568,4071,3953,0,10385,182.192982,7820,05:25:53,Half Day
16,bikash@uplora.live,2026-04-01,105,50,45,50,27,11084,8275,7979,0,21608,205.790476,16883,10:04:52,Present
17,deepak@uplora.live,2026-04-01,143,95,57,90,37,8833,4741,4482,22,20825,145.629371,14390,09:14:18,Present
18,dhruv@uplora.live,2026-04-01,70,61,26,47,18,6640,4776,4626,0,11489,164.128571,8339,06:02:09,Warning
19,harish@uplora.live,2026-04-01,38,23,10,23,8,3974,2672,2654,78,4622,121.631579,2912,03:23:16,Absent
20,imran@uplora.live,2026-04-01,50,15,14,8,6,3750,2128,2014,187,35324,706.480000,33074,11:51:14,Present
21,irfan@uplora.live,2026-04-01,74,64,30,39,20,8386,6562,6396,0,8530,115.270270,5200,05:41:56,Half Day
22,jaideep@uplora.live,2026-04-01,95,87,50,61,37,8886,6680,6494,0,25344,266.778947,21069,10:30:30,Present
23,jaya@uplora.live,2026-04-01,120,96,43,32,28,6040,2587,2398,0,13596,113.300000,8196,06:27:16,Warning
24,junaid@uplora.live,2026-04-01,146,139,53,26,35,9358,4680,4404,48,15376,105.315068,8806,07:52:14,Warning
25,karishma@uplora.live,2026-04-01,47,26,16,22,6,1794,500,332,0,7277,154.829787,5162,03:31:11,Absent
26,kartik@uplora.live,2026-04-01,96,56,28,43,16,5291,2553,2391,0,16808,175.083333,12488,07:08:19,Warning
27,lakhan@uplora.live,2026-04-01,123,108,51,106,31,5777,3228,2945,0,16248,132.097561,10713,07:07:05,Warning
28,mayank@uplora.live,2026-03-31,48,32,19,32,17,3859,2957,2905,0,26198,545.791667,24038,09:20:57,Present
29,mayank@uplora.live,2026-04-01,1,1,0,0,0,13,0,0,0,0,0.000000,0,01:00:13,Absent
30,mujeeb@uplora.live,2026-04-01,238,220,77,91,27,10989,3572,2932,0,20904,87.831933,10194,09:51:33,Present
31,naman@uplora.live,2026-04-01,144,94,51,109,28,7435,3489,3117,0,28416,197.333333,21936,10:57:31,Present
32,nikita@uplora.live,2026-04-01,195,125,63,54,32,10135,4906,4551,0,19566,100.338462,10791,09:15:01,Present
33,nirvik@uplora.live,2026-04-01,150,93,58,70,42,13551,9491,9297,0,20763,138.420000,14013,10:31:54,Present
34,nishita@uplora.live,2026-03-31,11,9,4,7,4,614,435,435,0,3079,279.909091,2584,02:01:33,Absent
35,omkar@uplora.live,2026-04-01,44,22,17,29,13,3024,1961,1906,0,7580,172.272727,5600,03:56:44,Absent
36,prakash@uplora.live,2026-04-01,138,94,59,69,37,10566,6904,6572,2,18701,135.514493,12491,09:07:47,Present
37,prashant@uplora.live,2026-04-01,77,60,35,55,20,4127,2782,2526,7,28421,369.103896,24956,10:02:28,Present
38,raghav@uplora.live,2026-04-01,90,63,35,59,19,7095,4786,4559,18,23106,256.733333,19056,09:23:21,Present
39,rahmatullah@uplora.live,2026-04-01,3,3,2,0,1,136,72,57,0,117,39.000000,0,01:04:13,Absent
40,reyansh@uplora.live,2026-03-31,8,5,3,5,3,386,267,267,0,556,69.500000,196,01:15:42,Absent
41,rizwana@uplora.live,2026-04-01,108,72,42,64,19,5102,2252,1882,0,12338,114.240741,7478,05:50:40,Half Day
42,sabina@uplora.live,2026-04-01,138,73,55,47,33,8977,5616,5260,23,17443,126.398551,11233,08:20:20,Warning
43,samar@uplora.live,2026-04-01,163,114,42,93,19,7597,3043,2728,0,23004,141.128834,15669,09:30:01,Present
44,sandhya@uplora.live,2026-04-01,162,131,52,96,33,9276,4600,4319,0,22919,141.475309,15629,09:56:35,Present
45,shaqib@uplora.live,2026-03-31,180,124,69,89,51,9528,6707,6389,0,24429,135.716667,16329,10:25:57,Present
46,sunita@uplora.live,2026-04-01,181,157,63,100,25,7948,2656,2082,0,21112,116.640884,12967,09:04:20,Present
47,swati@uplora.live,2026-04-01,177,78,56,75,27,9013,3718,3262,0,28106,158.790960,20141,11:18:39,Present
48,upasana@uplora.live,2026-03-31,10,5,5,4,1,326,170,84,0,2358,235.800000,1908,01:44:44,Absent
49,vidhya@uplora.live,2026-04-01,124,59,59,63,38,6772,4593,4271,0,14123,113.895161,8543,06:48:15,Warning

In [99]:
AB = A['Attendance'].unique()
AB

array(['Absent', 'Warning', 'Present', 'Half Day'], dtype=object)

In [100]:
ref

,Dialer,Dialer Name,Employee Code,Full Name,Pool,TL,Vertical,Location,CRM ID
0,Stringee,ankit,U-1005,Ankit,RM,Virat,MarketBhai,DXB,ankit@uplora.live
1,Stringee,jaideep,E-1418,Jaideep,RM,Virat,MarketBhai,DXB,jaideep@uplora.live
2,Stringee,rahmatullah,E-1381,Rahmatullah,RM,Virat,MarketBhai,DXB,rahmatullah@uplora.live
3,Stringee,sabina,U-1039,Sabina,RM,Pranil,MarketBhai,DXB,sabina@uplora.live
4,Stringee,abdul,E-1236,Abdul,P1,Sameer,MarketBhai,DXB,abdul@uplora.live
...,...,...,...,...,...,...,...,...,...
67,Stringee,prashant,NaN,Prashant A,Pool 5,Virat,MarketBhai,DXB,prashant@uplora.live
68,Stringee,samrat,NaN,Samrat A,Pool 5,Virat,MarketBhai,DXB,samrat@uplora.live
69,Stringee,vidhya,NaN,Vidhya A,Pool 5,Virat,MarketBhai,DXB,vidhya@uplora.live
70,Uno,aarzoo,NaN,Aarzoo,Pool 5,Virat,MarketBhai,DXB,NaN
71,Uno,disha,NaN,Disha,Pool 5,Virat,MarketBhai,DXB,disha@uplora.live

In [101]:
# Filter unique CRM ID and select specific columns
unique_crm_ref = ref.drop_duplicates(subset=['CRM ID'])[['CRM ID','Employee Code', 'Full Name','Pool', 'TL','Vertical']]

unique_crm_ref

,CRM ID,Employee Code,Full Name,Pool,TL,Vertical
0,ankit@uplora.live,U-1005,Ankit,RM,Virat,MarketBhai
1,jaideep@uplora.live,E-1418,Jaideep,RM,Virat,MarketBhai
2,rahmatullah@uplora.live,E-1381,Rahmatullah,RM,Virat,MarketBhai
3,sabina@uplora.live,U-1039,Sabina,RM,Pranil,MarketBhai
4,abdul@uplora.live,E-1236,Abdul,P1,Sameer,MarketBhai
...,...,...,...,...,...,...
67,prashant@uplora.live,NaN,Prashant A,Pool 5,Virat,MarketBhai
68,samrat@uplora.live,NaN,Samrat A,Pool 5,Virat,MarketBhai
69,vidhya@uplora.live,NaN,Vidhya A,Pool 5,Virat,MarketBhai
70,NaN,NaN,Aarzoo,Pool 5,Virat,MarketBhai
71,disha@uplora.live,NaN,Disha,Pool 5,Virat,MarketBhai

In [102]:
# Extract unique dates from DataFrame A
all_dates = A['Date'].unique()

# Create a DataFrame with all CRM IDs from unique_crm_ref and all dates
date_crm_combinations = pd.MultiIndex.from_product(
    [unique_crm_ref['CRM ID'], all_dates],
    names=['CRM ID', 'Date']
).to_frame(index=False)



merged = date_crm_combinations.merge(
    A,
    how='left',
    on=['CRM ID', 'Date']
).fillna(0)

In [103]:
merged

,CRM ID,Date,Total_Dialed_Calls,Unique_Dialed_Numbers,Total_Connected_Calls,Total_Number_of_Call_Gap,Total_Call_GT_30,Total_Duration,Total_Talk_Time,Total_Talk_Time_GT_30,Total_Connected_Hold_Time,Total_Gap_Duration,Avg_Gap_per_call,Gap Duration After Leverage,Login Hours,Attendance
0,ankit@uplora.live,2026-03-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0,0
1,ankit@uplora.live,2026-04-01,4.0,3.0,2.0,2.0,2.0,1196.0,1097.0,1097.0,0.0,22274.0,5568.500000,22094.0,07:31:10,Warning
2,jaideep@uplora.live,2026-03-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0,0
3,jaideep@uplora.live,2026-04-01,95.0,87.0,50.0,61.0,37.0,8886.0,6680.0,6494.0,0.0,25344.0,266.778947,21069.0,10:30:30,Present
4,rahmatullah@uplora.live,2026-03-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,vidhya@uplora.live,2026-04-01,124.0,59.0,59.0,63.0,38.0,6772.0,4593.0,4271.0,0.0,14123.0,113.895161,8543.0,06:48:15,Warning
128,0,2026-03-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0,0
129,0,2026-04-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0,0
130,disha@uplora.live,2026-03-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0,0
131,disha@uplora.live,2026-04-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0,0

In [104]:
# Outer-merge with unique_crm_ref to retain all CRM IDs
merged_df = unique_crm_ref.merge(
    merged,
    how='outer',
    on='CRM ID'
)

In [105]:
merged_df

,CRM ID,Employee Code,Full Name,Pool,TL,Vertical,Date,Total_Dialed_Calls,Unique_Dialed_Numbers,Total_Connected_Calls,...,Total_Call_GT_30,Total_Duration,Total_Talk_Time,Total_Talk_Time_GT_30,Total_Connected_Hold_Time,Total_Gap_Duration,Avg_Gap_per_call,Gap Duration After Leverage,Login Hours,Attendance
0,0,NaN,NaN,NaN,NaN,NaN,2026-03-31,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0,0
1,0,NaN,NaN,NaN,NaN,NaN,2026-04-01,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0,0
2,aayush@uplora.live,U-1124,Aayush,Dialer,KASIF,MarketBhai,2026-03-31,2.0,1.0,0.0,...,0.0,69.0,0.0,0.0,0.0,57.0,28.500000,0.0,01:02:06,Absent
3,aayush@uplora.live,U-1124,Aayush,Dialer,KASIF,MarketBhai,2026-04-01,7.0,7.0,2.0,...,1.0,514.0,217.0,207.0,0.0,1272.0,181.714286,957.0,01:29:46,Absent
4,abdul@uplora.live,E-1236,Abdul,P1,Sameer,MarketBhai,2026-03-31,1.0,1.0,1.0,...,1.0,600.0,600.0,600.0,0.0,0.0,0.000000,0.0,01:10:00,Absent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,vidhya@uplora.live,NaN,Vidhya A,Pool 5,Virat,MarketBhai,2026-03-31,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0,0
129,vidhya@uplora.live,NaN,Vidhya A,Pool 5,Virat,MarketBhai,2026-04-01,124.0,59.0,59.0,...,38.0,6772.0,4593.0,4271.0,0.0,14123.0,113.895161,8543.0,06:48:15,Warning
130,yug@uplora.live,U-1134,Yug,P4,KASIF,MarketBhai,2026-03-31,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0,0
131,yug@uplora.live,U-1134,Yug,P4,KASIF,MarketBhai,2026-04-01,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0,0
132,NaN,NaN,Aarzoo,Pool 5,Virat,MarketBhai,NaT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [106]:
# Replace NaN or missing values with 0
columns_to_format = ['Total_Dialed_Calls', 'Unique_Dialed_Numbers','Total_Connected_Calls','Total_Number_of_Call_Gap', 'Total_Call_GT_30','Total_Duration','Total_Talk_Time','Total_Talk_Time_GT_30','Total_Connected_Hold_Time','Total_Gap_Duration']
merged_df[columns_to_format] = merged_df[columns_to_format].fillna(0)

# Convert specified columns to integers
merged_df[columns_to_format] = merged_df[columns_to_format].astype(int)

# Reorder columns
formatted_df = merged_df[['Date', 'Pool', 'TL', 'CRM ID','Employee Code', 'Full Name', 'Vertical'] + [col for col in merged_df.columns if col not in ['Date', 'Pool', 'TL', 'CRM ID','Employee Code', 'Full Name', 'Vertical']]]

formatted_df

,Date,Pool,TL,CRM ID,Employee Code,Full Name,Vertical,Total_Dialed_Calls,Unique_Dialed_Numbers,Total_Connected_Calls,...,Total_Call_GT_30,Total_Duration,Total_Talk_Time,Total_Talk_Time_GT_30,Total_Connected_Hold_Time,Total_Gap_Duration,Avg_Gap_per_call,Gap Duration After Leverage,Login Hours,Attendance
0,2026-03-31,NaN,NaN,0,NaN,NaN,NaN,0,0,0,...,0,0,0,0,0,0,0.000000,0.0,0,0
1,2026-04-01,NaN,NaN,0,NaN,NaN,NaN,0,0,0,...,0,0,0,0,0,0,0.000000,0.0,0,0
2,2026-03-31,Dialer,KASIF,aayush@uplora.live,U-1124,Aayush,MarketBhai,2,1,0,...,0,69,0,0,0,57,28.500000,0.0,01:02:06,Absent
3,2026-04-01,Dialer,KASIF,aayush@uplora.live,U-1124,Aayush,MarketBhai,7,7,2,...,1,514,217,207,0,1272,181.714286,957.0,01:29:46,Absent
4,2026-03-31,P1,Sameer,abdul@uplora.live,E-1236,Abdul,MarketBhai,1,1,1,...,1,600,600,600,0,0,0.000000,0.0,01:10:00,Absent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,2026-03-31,Pool 5,Virat,vidhya@uplora.live,NaN,Vidhya A,MarketBhai,0,0,0,...,0,0,0,0,0,0,0.000000,0.0,0,0
129,2026-04-01,Pool 5,Virat,vidhya@uplora.live,NaN,Vidhya A,MarketBhai,124,59,59,...,38,6772,4593,4271,0,14123,113.895161,8543.0,06:48:15,Warning
130,2026-03-31,P4,KASIF,yug@uplora.live,U-1134,Yug,MarketBhai,0,0,0,...,0,0,0,0,0,0,0.000000,0.0,0,0
131,2026-04-01,P4,KASIF,yug@uplora.live,U-1134,Yug,MarketBhai,0,0,0,...,0,0,0,0,0,0,0.000000,0.0,0,0
132,NaT,Pool 5,Virat,NaN,NaN,Aarzoo,MarketBhai,0,0,0,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN

In [107]:
formatted_df.isnull().sum()

Date                            1
Pool                            2
TL                              2
CRM ID                          1
Employee Code                  21
Full Name                       2
Vertical                        2
Total_Dialed_Calls              0
Unique_Dialed_Numbers           0
Total_Connected_Calls           0
Total_Number_of_Call_Gap        0
Total_Call_GT_30                0
Total_Duration                  0
Total_Talk_Time                 0
Total_Talk_Time_GT_30           0
Total_Connected_Hold_Time       0
Total_Gap_Duration              0
Avg_Gap_per_call                1
Gap Duration After Leverage     1
Login Hours                     1
Attendance                      1
dtype: int64

In [108]:
def seconds_to_hhmmss(seconds):
    try:
        # If string, convert to float
        seconds = float(seconds)
    except:
        # If conversion fails (e.g., already hh:mm:ss string), treat as 0
        seconds = 0
    
    total_seconds = round(seconds)
    hours = total_seconds // 3600
    remaining = total_seconds % 3600
    minutes = remaining // 60
    secs = remaining % 60
    return f"{hours:02d}:{minutes:02d}:{secs:02d}"  # hh:mm:ss

columns_to_convert = [
    'Total_Duration', 
    'Total_Talk_Time', 
    'Total_Talk_Time_GT_30', 
    'Total_Connected_Hold_Time', 
    'Total_Gap_Duration',
    'Avg_Gap_per_call',
    'Gap Duration After Leverage'
]

# Fill NaN with 0 first
formatted_df[columns_to_convert] = formatted_df[columns_to_convert].fillna(0)

# Apply conversion
for col in columns_to_convert:
    formatted_df[col] = formatted_df[col].apply(seconds_to_hhmmss)

In [109]:
formatted_df = formatted_df.sort_values(by=['Date','CRM ID'])

In [110]:
formatted_df

,Date,Pool,TL,CRM ID,Employee Code,Full Name,Vertical,Total_Dialed_Calls,Unique_Dialed_Numbers,Total_Connected_Calls,...,Total_Call_GT_30,Total_Duration,Total_Talk_Time,Total_Talk_Time_GT_30,Total_Connected_Hold_Time,Total_Gap_Duration,Avg_Gap_per_call,Gap Duration After Leverage,Login Hours,Attendance
0,2026-03-31,NaN,NaN,0,NaN,NaN,NaN,0,0,0,...,0,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,0,0
2,2026-03-31,Dialer,KASIF,aayush@uplora.live,U-1124,Aayush,MarketBhai,2,1,0,...,0,00:01:09,00:00:00,00:00:00,00:00:00,00:00:57,00:00:28,00:00:00,01:02:06,Absent
4,2026-03-31,P1,Sameer,abdul@uplora.live,E-1236,Abdul,MarketBhai,1,1,1,...,1,00:10:00,00:10:00,00:10:00,00:00:00,00:00:00,00:00:00,00:00:00,01:10:00,Absent
6,2026-03-31,Pool 5,Virat,abhishek@uplora.live,NaN,Abhishek A,MarketBhai,0,0,0,...,0,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,0,0
8,2026-03-31,P4,KASIF,abiral@uplora.live,U-1145,Abiral,MarketBhai,0,0,0,...,0,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,2026-04-01,P3,Armaan,swati@uplora.live,U-1098,Swati,MarketBhai,177,78,56,...,27,02:30:13,01:01:58,00:54:22,00:00:00,07:48:26,00:02:39,05:35:41,11:18:39,Present
127,2026-04-01,P2,Armaan,upasana@uplora.live,U-1021,Upasana,MarketBhai,0,0,0,...,0,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,0,0
129,2026-04-01,Pool 5,Virat,vidhya@uplora.live,NaN,Vidhya A,MarketBhai,124,59,59,...,38,01:52:52,01:16:33,01:11:11,00:00:00,03:55:23,00:01:54,02:22:23,06:48:15,Warning
131,2026-04-01,P4,KASIF,yug@uplora.live,U-1134,Yug,MarketBhai,0,0,0,...,0,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,0,0
132,NaT,Pool 5,Virat,NaN,NaN,Aarzoo,MarketBhai,0,0,0,...,0,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,NaN,NaN

In [111]:
formatted_df['Attendance'].unique()

array([0, 'Absent', 'Present', 'Warning', 'Half Day', nan], dtype=object)

In [112]:

formatted_df['Login Hours'] = formatted_df['Login Hours'].apply(lambda x: '00:00:00' if x == 0 else x)

formatted_df['Attendance'] = formatted_df['Attendance'].apply(lambda x: 'Absent' if x == 0 else x)

In [113]:
formatted_df

,Date,Pool,TL,CRM ID,Employee Code,Full Name,Vertical,Total_Dialed_Calls,Unique_Dialed_Numbers,Total_Connected_Calls,...,Total_Call_GT_30,Total_Duration,Total_Talk_Time,Total_Talk_Time_GT_30,Total_Connected_Hold_Time,Total_Gap_Duration,Avg_Gap_per_call,Gap Duration After Leverage,Login Hours,Attendance
0,2026-03-31,NaN,NaN,0,NaN,NaN,NaN,0,0,0,...,0,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,Absent
2,2026-03-31,Dialer,KASIF,aayush@uplora.live,U-1124,Aayush,MarketBhai,2,1,0,...,0,00:01:09,00:00:00,00:00:00,00:00:00,00:00:57,00:00:28,00:00:00,01:02:06,Absent
4,2026-03-31,P1,Sameer,abdul@uplora.live,E-1236,Abdul,MarketBhai,1,1,1,...,1,00:10:00,00:10:00,00:10:00,00:00:00,00:00:00,00:00:00,00:00:00,01:10:00,Absent
6,2026-03-31,Pool 5,Virat,abhishek@uplora.live,NaN,Abhishek A,MarketBhai,0,0,0,...,0,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,Absent
8,2026-03-31,P4,KASIF,abiral@uplora.live,U-1145,Abiral,MarketBhai,0,0,0,...,0,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,Absent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,2026-04-01,P3,Armaan,swati@uplora.live,U-1098,Swati,MarketBhai,177,78,56,...,27,02:30:13,01:01:58,00:54:22,00:00:00,07:48:26,00:02:39,05:35:41,11:18:39,Present
127,2026-04-01,P2,Armaan,upasana@uplora.live,U-1021,Upasana,MarketBhai,0,0,0,...,0,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,Absent
129,2026-04-01,Pool 5,Virat,vidhya@uplora.live,NaN,Vidhya A,MarketBhai,124,59,59,...,38,01:52:52,01:16:33,01:11:11,00:00:00,03:55:23,00:01:54,02:22:23,06:48:15,Warning
131,2026-04-01,P4,KASIF,yug@uplora.live,U-1134,Yug,MarketBhai,0,0,0,...,0,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,Absent
132,NaT,Pool 5,Virat,NaN,NaN,Aarzoo,MarketBhai,0,0,0,...,0,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,NaN,NaN

In [114]:
# Convert 'Total Call Duration' to hh:mm:ss format
Dialers["Total Call Duration"] = Dialers["Total Call Duration"].apply(lambda x: str(x).split(" ")[-1])
Dialers['Number'] = "'" + Dialers['Number'].astype(str)

In [115]:
D = Dialers.drop(columns=['Talk Time (seconds)','Hold Time (seconds)','Total Duration (seconds)','Gap Duration (seconds)','Dialer'])
D['Number'] = D['Number'].astype(str).str.split('.').str[0]
D

,Source,Date,Dialer Name,Number,Call Status,Call Start Time,Total Call Duration,Talk Time,Hold Time,Employee Code,Full Name,Pool,TL,Vertical,Location,CRM ID,Call Gap,Gap Duration
0,Uno,2026-03-31,aayush,'9892977091,not connected,2026-03-31 11:37:42,00:00:36,00:00:36,00:00:00,U-1124,Aayush,Dialer,KASIF,MarketBhai,IND,aayush@uplora.live,No,00:00:00
1,Uno,2026-03-31,aayush,'9892977091,not connected,2026-03-31 11:39:15,00:00:33,00:00:33,00:00:00,U-1124,Aayush,Dialer,KASIF,MarketBhai,IND,aayush@uplora.live,No,00:00:57
2,Uno,2026-03-31,abdul,'9079131246,connected,2026-03-31 12:16:52,00:10:00,00:10:00,00:00:00,E-1236,Abdul,P1,Sameer,MarketBhai,DXB,abdul@uplora.live,No,00:00:00
3,Uno,2026-03-31,advik,'9194259045,not connected,2026-03-31 13:08:01,00:00:21,00:00:21,00:00:00,U-1130,Advik,Dialer,KASIF,MarketBhai,IND,advik@uplora.live,No,00:00:00
4,Uno,2026-03-31,advik,'9425904504,not connected,2026-03-31 13:09:13,00:00:37,00:00:37,00:00:00,U-1130,Advik,Dialer,KASIF,MarketBhai,IND,advik@uplora.live,No,00:00:51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4278,Stringee,2026-04-01,vidhya,'918445530137,connected,2026-04-01 18:24:51,00:00:44,00:00:36,00:00:00,NaN,Vidhya A,Pool 5,Virat,MarketBhai,DXB,vidhya@uplora.live,Yes,00:01:04
4279,Stringee,2026-04-01,vidhya,'918445530137,connected,2026-04-01 18:25:40,00:01:11,00:01:05,00:00:00,NaN,Vidhya A,Pool 5,Virat,MarketBhai,DXB,vidhya@uplora.live,No,00:00:05
4280,Stringee,2026-04-01,vidhya,'919205330143,connected,2026-04-01 18:27:18,00:00:25,00:00:04,00:00:00,NaN,Vidhya A,Pool 5,Virat,MarketBhai,DXB,vidhya@uplora.live,No,00:00:27
4281,Stringee,2026-04-01,vidhya,'919205330143,connected,2026-04-01 18:27:57,00:01:07,00:00:42,00:00:00,NaN,Vidhya A,Pool 5,Virat,MarketBhai,DXB,vidhya@uplora.live,No,00:00:14
4282,Stringee,2026-04-01,vidhya,'916299281276,not connected,2026-04-01 18:32:30,00:00:11,00:00:00,00:00:00,NaN,Vidhya A,Pool 5,Virat,MarketBhai,DXB,vidhya@uplora.live,No,00:03:26

In [116]:


# Step 1: Convert datetime and timedelta columns
D['Call Start Time'] = pd.to_datetime(D['Call Start Time'])
D['Talk Time'] = pd.to_timedelta(D['Talk Time'])
D['Total Call Duration'] = pd.to_timedelta(D['Total Call Duration'])
D['hour'] = D['Call Start Time'].dt.hour

# Step 2: Define interval buckets
def get_interval(hour):
    if hour < 8: return '0 to 8 AM'
    elif hour < 9: return '8 to 9 AM'
    elif hour < 10: return '9 to 10 AM'
    elif hour < 11: return '10 to 11 AM'
    elif hour < 12: return '11 to 12 PM'
    elif hour < 13: return '12 to 13 PM'
    elif hour < 14: return '13 to 14 PM'
    elif hour < 15: return '14 to 15 PM'
    elif hour < 16: return '15 to 16 PM'
    elif hour < 17: return '16 to 17 PM'
    elif hour < 18: return '17 to 18 PM'
    elif hour < 19: return '18 to 19 PM'
    elif hour < 20: return '19 to 20 PM'
    else: return '20+'

D['Interval'] = D['hour'].apply(get_interval)

# Step 3: Create pivot for call counts
call_counts = pd.pivot_table(
    D,
    index=['CRM ID','Full Name', 'Pool', 'TL'],
    columns='Interval',
    values='Date',  # any non-null column
    aggfunc='count',
    fill_value=0
)

# Step 4: Pivot for Talk Time and Total Call Duration
durations = pd.pivot_table(
    D,
    index=['CRM ID','Full Name', 'Pool', 'TL'],
    columns='Interval',
    values=['Talk Time', 'Total Call Duration'],
    aggfunc='sum',
    fill_value=pd.Timedelta(0)
)


unique_calls = pd.pivot_table(
    D,
    index=['CRM ID', 'Full Name', 'Pool', 'TL'],
    columns='Interval',
    values='Number',
    aggfunc=pd.Series.nunique,
    fill_value=0
)
unique_calls.columns = [f'{col} - Unique Calls' for col in unique_calls.columns]
# Step 5: Format the timedelta columns as hh:mm:ss
durations = durations.applymap(lambda x: str(x) if pd.notnull(x) else '00:00:00')

# Step 6: Flatten column names
call_counts.columns = [f'{col} - Calls' for col in call_counts.columns]
durations.columns = [f'{interval} - {metric}' for metric, interval in durations.columns]

# Step 7: Combine everything
final_df_cre = pd.concat([call_counts, unique_calls, durations], axis=1).reset_index()

C:\Users\Akhil\AppData\Local\Temp\ipykernel_10448\1927572369.py:57: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  durations = durations.applymap(lambda x: str(x) if pd.notnull(x) else '00:00:00')

In [117]:
final_df_cre

,CRM ID,Full Name,Pool,TL,0 to 8 AM - Calls,10 to 11 AM - Calls,11 to 12 PM - Calls,12 to 13 PM - Calls,13 to 14 PM - Calls,14 to 15 PM - Calls,...,13 to 14 PM - Total Call Duration,14 to 15 PM - Total Call Duration,15 to 16 PM - Total Call Duration,16 to 17 PM - Total Call Duration,17 to 18 PM - Total Call Duration,18 to 19 PM - Total Call Duration,19 to 20 PM - Total Call Duration,20+ - Total Call Duration,8 to 9 AM - Total Call Duration,9 to 10 AM - Total Call Duration
0,aayush@uplora.live,Aayush,Dialer,KASIF,7,0,2,0,0,0,...,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
1,abdul@uplora.live,Abdul,P1,Sameer,5,0,0,1,0,0,...,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
2,abhishek@uplora.live,Abhishek A,Pool 5,Virat,5,0,0,0,0,0,...,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
3,abiral@uplora.live,Abiral,P4,KASIF,0,0,1,29,33,26,...,0 days 00:18:24,0 days 00:46:19,0 days 00:15:51,0 days 00:22:40,0 days 00:22:15,0 days 00:12:59,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
4,advik@uplora.live,Advik,Dialer,KASIF,0,0,0,0,9,3,...,0 days 00:06:44,0 days 00:02:32,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
5,aelina@uplora.live,Aelina,Dialer,KASIF,2,0,0,0,0,0,...,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
6,ajit@uplora.live,Ajit,P2- Dialer,Armaan,0,8,14,29,12,24,...,0 days 00:40:06,0 days 00:28:59,0 days 00:14:21,0 days 00:16:07,0 days 00:11:46,0 days 00:10:39,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:14:29
7,akhil@uplora.live,Akhil,P4 - Dialer,KASIF,0,3,4,31,7,0,...,0 days 00:04:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
8,akshay@uplora.live,Akshay A,Pool 5,Virat,2,8,26,15,22,14,...,0 days 00:13:43,0 days 00:23:07,0 days 00:09:35,0 days 00:15:54,0 days 00:12:25,0 days 00:22:10,0 days 00:00:16,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
9,anita@uplora.live,Anita,P1,Sameer,3,0,0,0,0,0,...,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
10,ankit@uplora.live,Ankit,RM,Virat,0,1,1,0,0,0,...,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:16:02,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
11,anushka@uplora.live,Anushka A,Pool 5,Virat,0,11,19,14,4,16,...,0 days 00:02:05,0 days 00:15:43,0 days 00:24:16,0 days 00:10:13,0 days 00:11:59,0 days 00:12:27,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:09:28
12,atif@uplora.live,Atif,RM,Pranil,0,0,0,0,20,17,...,0 days 00:20:07,0 days 00:17:30,0 days 00:23:08,0 days 00:08:00,0 days 00:11:28,0 days 00:10:05,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
13,ayushman@uplora.live,Ayushman,RM,Pranil,0,0,0,1,6,2,...,0 days 00:19:43,0 days 00:26:03,0 days 00:00:42,0 days 00:21:05,0 days 00:17:41,0 days 00:07:25,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
14,bikash@uplora.live,Bikash,P1,Sameer,0,6,8,12,10,1,...,0 days 00:07:51,0 days 00:00:27,0 days 00:14:59,0 days 00:09:26,0 days 00:10:50,0 days 00:24:24,0 days 00:40:52,0 days 00:00:00,0 days 00:00:00,0 days 00:01:14
15,deepak@uplora.live,Deepak,P4,KASIF,0,3,12,28,8,18,...,0 days 00:11:30,0 days 00:19:11,0 days 00:13:24,0 days 00:20:14,0 days 00:11:57,0 days 00:13:35,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:20:40
16,dhruv@uplora.live,Dhruv,RM,Pranil,0,0,0,3,8,18,...,0 days 00:07:02,0 days 00:11:11,0 days 00:19:28,0 days 00:11:43,0 days 00:26:00,0 days 00:03:31,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
17,harish@uplora.live,Harish,P4 - Dialer,KASIF,0,0,0,0,0,3,...,0 days 00:00:00,0 days 00:02:23,0 days 00:09:30,0 days 00:18:16,0 days 00:16:03,0 days 00:20:02,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
18,imran@uplora.live,Imran,P4 - Dialer,KASIF,4,0,0,0,0,0,...,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:11:06,0 days 00:37:16,0 days 00:12:13,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
19,irfan@uplora.live,Irfan,RM,Pranil,0,0,0,7,17,9,...,0 days 00:34:24,0 days 00:07:17,0 days 00:14:43,0 days 00:45:21,0 days 00:30:09,0 days 00:05:42,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
20,jaideep@uplora.live,Jaideep,RM,Virat,24,4,9,10,12,9,...,0 days 00:17:27,0 days 00:18:42,0 days 00:08:10,0 days 00:20:05,0 days 00:28:20,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
21,jaya@uplora.live,Jaya,P2,Armaan,0,6,13,18,17,24,...,0 days 00:18:37,0 days 00:17:47,0 days 00:29:46,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:43
22,junaid@uplora.live,Junaid,P1,Sameer,0,8,13,19,20,16,...,0 days 00:21:40,0 days 00:13:37,0 days 00:14:51,0 days 00:17:34,0 days 00:20:50,0 days 00:09:32,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
23,karishma@uplora.live,Karishma,P2,Armaan,0,0,0,0,0,1,...,0 days 00:00:00,0 days 00:02:00,0 days 00:00:00,0 days 00:09:05,0 days 00:16:52,0 days 00:01:57,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
24,kartik@uplora.live,Kartik,RM,Pranil,0,0,0,3,1,8,...,0 days 00:03:01,0 days 00:04:47,0 days 00:13:26,0 days 00:20:18,0 days 00:24:11,0 days 00:13:52,0 days 00:07:56,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
25,lakhan@uplora.live,Lakhan A,Pool 5,Virat,0,3,10,22,14,19,...,0 days 00:09:27,0 days 00:15:36,0 days 00:14:13,0 days 00:09:19,0 days 00:12:28,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
26,mayank@uplora.live,Mayank,P1,Sameer,1,22,3,4,0,0,...,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:15,0 days 00:02:54,0 days 00:11:27,0 days 00:01:09,0 days 00:00:00,0 days 00:00:00,0 days 00:02:38
27,mujeeb@uplora.live,Mujeeb,P4,KASIF,0,10,9,30,15,35,...,0 days 00:10:29,0 days 00:28:55,0 days 00:31:09,0 days 00:21:12,0 days 00:22:46,0 days 00:19:35,0 days 00:01:51,0 days 00:00:00,0 days 00:00:00,0 days 00:12:08
28,naman@uplora.live,Naman,P1,Sameer,0,14,11,14,10,12,...,0 days 00:05:51,0 days 00:14:59,0 days 00:15:45,0 days 00:17:59,0 days 00:11:30,0 days 00:09:54,0 days 00:02:28,0 days 00:00:54,0 days 00:00:00,0 days 00:08:07
29,nikita@uplora.live,Nikita,P2- Dialer,Armaan,0,14,14,30,11,22,...,0 days 00:05:07,0 days 00:18:01,0 days 00:32:30,0 days 00:19:00,0 days 00:19:38,0 days 00:23:44,0 days 00:08:22,0 days 00:00:00,0 days 00:00:00,0 days 00:00:18
30,nirvik@uplora.live,Nirvik,P1,Sameer,0,9,9,11,18,26,...,0 days 00:22:03,0 days 00:39:32,0 days 00:20:54,0 days 00:41:10,0 days 00:17:17,0 days 00:10:55,0 days 00:00:52,0 days 00:00:00,0 days 00:01:18,0 days 00:13:20
31,nishita@uplora.live,Nishita A,Pool 5,Virat,0,0,0,0,9,2,...,0 days 00:08:51,0 days 00:01:23,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
32,omkar@uplora.live,Omkar,P4 - Dialer,KASIF,0,0,0,0,0,0,...,0 days 00:00:00,0 days 00:00:00,0 days 00:11:36,0 days 00:15:47,0 days 00:11:58,0 days 00:10:46,0 days 00:00:17,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
33,prakash@uplora.live,Prakash,P2,Armaan,0,10,18,19,5,29,...,0 days 00:10:44,0 days 00:18:08,0 days 00:19:17,0 days 00:14:59,0 days 00:13:06,0 days 00:26:05,0 days 00:00:51,0 days 00:00:00,0 days 00:00:00,0 days 00:03:28
34,prashant@uplora.live,Prashant A,Pool 5,Virat,1,2,12,12,6,13,...,0 days 00:03:52,0 days 00:08:53,0 days 00:06:28,0 days 00:16:06,0 days 00:05:01,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
35,raghav@uplora.live,Raghav,P2,Armaan,0,4,18,9,9,11,...,0 days 00:06:43,0 days 00:31:37,0 days 00:03:55,0 days 00:15:09,0 days 00:12:05,0 days 00:00:02,0 days 00:02:10,0 days 00:00:00,0 days 00:00:00,0 days 00:00:23
36,rahmatullah@uplora.live,Rahmatullah,RM,Virat,3,0,0,0,0,0,...,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
37,reyansh@uplora.live,Reyansh,Dialer,KASIF,0,0,0,0,8,0,...,0 days 00:06:26,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
38,rizwana@uplora.live,Rizwana,P2- Dialer,Armaan,0,0,4,18,20,21,...,0 days 00:14:03,0 days 00:18:32,0 days 00:16:33,0 days 00:13:55,0 days 00:05:52,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
39,sabina@uplora.live,Sabina,RM,Pranil,0,1,0,15,24,37,...,0 days 00:32:34,0 days 00:18:59,0 days 00:34:42,0 days 00:18:07,0 days 00:18:14,0 days 00:14:57,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
40,samar@uplora.live,Samar,P1,Sameer,0,7,8,23,19,13,...,0 days 00:13:50,0 days 00:08:20,0 days 00:13:31,0 days 00:11:09,0 days 00:17:11,0 days 00:18:48,0 days 00:05:50,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
41,sandhya@uplora.live,Sandhya,P2- Dialer,Armaan,0,7,19,14,10,20,...,0 days 00:05:59,0 days 00:10:12,0 days 00:22:10,0 days 00:09:48,0 days 00:17:14,0 days 00:33:41,0 days 00:09:21,0 days 00:00:00,0 days 00:00:00,0 days 00:07:21
42,shaqib@uplora.live,Shaqib,P1,Sameer,0,20,27,31,18,23,...,0 days 00:12:35,0 days 00:20:04,0 days 00:07:56,0 days 00:08:12,0 days 00:01:05,0 days 00:14:12,0 days 00:18:27,0 days 00:03:16,0 days 00:00:00,0 days 00:21:51
43,sunita@uplora.live,Sunita,P4 - Dialer,KASIF,0,13,24,24,24,24,...,0 days 00:14:06,0 days 00:14:44,0 days 00:15:39,0 days 00:09:44,0 days 00:15:38,0 days 00:04:54,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:06:23
44,swati@uplora.live,Swati,P3,Armaan,0,0,18,19,18,17,...,0 days 00:13:11,0 days 00:11:40,0 days 00:21:09,0 days 00:11:49,0 days 00:18:15,0 days 00:17:50,0 days 00:19:15,0 days 00:00:00,0 days 00:06:05,0 days 00:02:39
45,upasana@uplora.live,Upasana,P2,Armaan,0,10,0,0,0,0,...,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
46,vidhya@uplora.live,Vidhya A,Pool 5,Virat,0,0,12,24,13,18,...,0 days 00:18:51,0 days 00:24:14,0 days 00:30:02,0 days 00:01:27,0 days 00:14:20,0 days 00:12:13,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00

In [118]:
# Combine all: call counts, durations, and unique dialers
final_df_cre = pd.concat([call_counts, durations, unique_calls], axis=1).reset_index()

In [119]:
final_df_cre.columns

Index(['CRM ID', 'Full Name', 'Pool', 'TL', '0 to 8 AM - Calls',
       '10 to 11 AM - Calls', '11 to 12 PM - Calls', '12 to 13 PM - Calls',
       '13 to 14 PM - Calls', '14 to 15 PM - Calls', '15 to 16 PM - Calls',
       '16 to 17 PM - Calls', '17 to 18 PM - Calls', '18 to 19 PM - Calls',
       '19 to 20 PM - Calls', '20+ - Calls', '8 to 9 AM - Calls',
       '9 to 10 AM - Calls', '0 to 8 AM - Talk Time',
       '10 to 11 AM - Talk Time', '11 to 12 PM - Talk Time',
       '12 to 13 PM - Talk Time', '13 to 14 PM - Talk Time',
       '14 to 15 PM - Talk Time', '15 to 16 PM - Talk Time',
       '16 to 17 PM - Talk Time', '17 to 18 PM - Talk Time',
       '18 to 19 PM - Talk Time', '19 to 20 PM - Talk Time', '20+ - Talk Time',
       '8 to 9 AM - Talk Time', '9 to 10 AM - Talk Time',
       '0 to 8 AM - Total Call Duration', '10 to 11 AM - Total Call Duration',
       '11 to 12 PM - Total Call Duration',
       '12 to 13 PM - Total Call Duration',
       '13 to 14 PM - Total Call Duration',
       '14 to 15 PM - Total Call Duration',
       '15 to 16 PM - Total Call Duration',
       '16 to 17 PM - Total Call Duration',
       '17 to 18 PM - Total Call Duration',
       '18 to 19 PM - Total Call Duration',
       '19 to 20 PM - Total Call Duration', '20+ - Total Call Duration',
       '8 to 9 AM - Total Call Duration', '9 to 10 AM - Total Call Duration',
       '0 to 8 AM - Unique Calls', '10 to 11 AM - Unique Calls',
       '11 to 12 PM - Unique Calls', '12 to 13 PM - Unique Calls',
       '13 to 14 PM - Unique Calls', '14 to 15 PM - Unique Calls',
       '15 to 16 PM - Unique Calls', '16 to 17 PM - Unique Calls',
       '17 to 18 PM - Unique Calls', '18 to 19 PM - Unique Calls',
       '19 to 20 PM - Unique Calls', '20+ - Unique Calls',
       '8 to 9 AM - Unique Calls', '9 to 10 AM - Unique Calls'],
      dtype='object')

In [120]:
all_columns = final_df_cre.columns.tolist()

# Identify time slot prefixes (ensure consistency with how they're used in the dataframe)
time_slots = [
    "0 to 8 AM", "8 to 9 AM", "9 to 10 AM", "10 to 11 AM",
    "11 to 12 PM", "12 to 13 PM", "13 to 14 PM", "14 to 15 PM",
    "15 to 16 PM", "16 to 17 PM", "17 to 18 PM", "18 to 19 PM", "19 to 20 PM", "20+"
]

# Get non-time-based columns (fixed fields like name, CRM ID, etc.)
fixed_columns = [col for col in all_columns if all(slot not in col for slot in time_slots)]

# Interleave Calls, Talk Time, Total Call Duration, and Unique Dialers
interleaved_columns = []
for slot in time_slots:
    call_col = f"{slot} - Calls"
    talk_col = f"{slot} - Talk Time"
    total_col = f"{slot} - Total Call Duration"
    unique_calls_col = f"{slot} - Unique Calls"
    
    # Append only if the column exists
    if call_col in all_columns:
        interleaved_columns.append(call_col)
    if talk_col in all_columns:
        interleaved_columns.append(talk_col)
    if total_col in all_columns:
        interleaved_columns.append(total_col)
    if unique_calls_col in all_columns:
        interleaved_columns.append(unique_calls_col)

# Final column order
new_column_order = fixed_columns + interleaved_columns

# Reorder the DataFrame
df_reordered = final_df_cre[new_column_order]

# Display (or export)
print(df_reordered.head())

                 CRM ID   Full Name    Pool      TL  0 to 8 AM - Calls  \
0    aayush@uplora.live      Aayush  Dialer   KASIF                  7
1     abdul@uplora.live       Abdul      P1  Sameer                  5
2  abhishek@uplora.live  Abhishek A  Pool 5   Virat                  5
3    abiral@uplora.live      Abiral      P4   KASIF                  0
4     advik@uplora.live       Advik  Dialer   KASIF                  0

  0 to 8 AM - Talk Time 0 to 8 AM - Total Call Duration  \
0       0 days 00:03:37                 0 days 00:08:34
1       0 days 00:01:17                 0 days 00:04:44
2       0 days 00:00:45                 0 days 00:02:48
3       0 days 00:00:00                 0 days 00:00:00
4       0 days 00:00:00                 0 days 00:00:00

   0 to 8 AM - Unique Calls  8 to 9 AM - Calls 8 to 9 AM - Talk Time  ...  \
0                         7                  0       0 days 00:00:00  ...
1                         2                  0       0 days 00:00:00  ...
2                         5                  0       0 days 00:00:00  ...
3                         0                  0       0 days 00:00:00  ...
4                         0                  0       0 days 00:00:00  ...

  18 to 19 PM - Total Call Duration  18 to 19 PM - Unique Calls  \
0                   0 days 00:00:00                           0
1                   0 days 00:00:00                           0
2                   0 days 00:00:00                           0
3                   0 days 00:12:59                           4
4                   0 days 00:00:00                           0

   19 to 20 PM - Calls 19 to 20 PM - Talk Time  \
0                    0         0 days 00:00:00
1                    0         0 days 00:00:00
2                    0         0 days 00:00:00
3                    0         0 days 00:00:00
4                    0         0 days 00:00:00

  19 to 20 PM - Total Call Duration  19 to 20 PM - Unique Calls  20+ - Calls  \
0                   0 days 00:00:00                           0            0
1                   0 days 00:00:00                           0            0
2                   0 days 00:00:00                           0            0
3                   0 days 00:00:00                           0            0
4                   0 days 00:00:00                           0            0

   20+ - Talk Time 20+ - Total Call Duration  20+ - Unique Calls
0  0 days 00:00:00           0 days 00:00:00                   0
1  0 days 00:00:00           0 days 00:00:00                   0
2  0 days 00:00:00           0 days 00:00:00                   0
3  0 days 00:00:00           0 days 00:00:00                   0
4  0 days 00:00:00           0 days 00:00:00                   0

[5 rows x 60 columns]

In [121]:
df_reordered

,CRM ID,Full Name,Pool,TL,0 to 8 AM - Calls,0 to 8 AM - Talk Time,0 to 8 AM - Total Call Duration,0 to 8 AM - Unique Calls,8 to 9 AM - Calls,8 to 9 AM - Talk Time,...,18 to 19 PM - Total Call Duration,18 to 19 PM - Unique Calls,19 to 20 PM - Calls,19 to 20 PM - Talk Time,19 to 20 PM - Total Call Duration,19 to 20 PM - Unique Calls,20+ - Calls,20+ - Talk Time,20+ - Total Call Duration,20+ - Unique Calls
0,aayush@uplora.live,Aayush,Dialer,KASIF,7,0 days 00:03:37,0 days 00:08:34,7,0,0 days 00:00:00,...,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
1,abdul@uplora.live,Abdul,P1,Sameer,5,0 days 00:01:17,0 days 00:04:44,2,0,0 days 00:00:00,...,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
2,abhishek@uplora.live,Abhishek A,Pool 5,Virat,5,0 days 00:00:45,0 days 00:02:48,5,0,0 days 00:00:00,...,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
3,abiral@uplora.live,Abiral,P4,KASIF,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:12:59,4,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
4,advik@uplora.live,Advik,Dialer,KASIF,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
5,aelina@uplora.live,Aelina,Dialer,KASIF,2,0 days 00:07:05,0 days 00:08:13,2,0,0 days 00:00:00,...,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
6,ajit@uplora.live,Ajit,P2- Dialer,Armaan,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:10:39,3,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
7,akhil@uplora.live,Akhil,P4 - Dialer,KASIF,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
8,akshay@uplora.live,Akshay A,Pool 5,Virat,2,0 days 00:00:39,0 days 00:01:08,2,0,0 days 00:00:00,...,0 days 00:22:10,9,1,0 days 00:00:00,0 days 00:00:16,1,0,0 days 00:00:00,0 days 00:00:00,0
9,anita@uplora.live,Anita,P1,Sameer,3,0 days 00:01:59,0 days 00:03:14,1,0,0 days 00:00:00,...,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
10,ankit@uplora.live,Ankit,RM,Virat,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:16:02,1,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
11,anushka@uplora.live,Anushka A,Pool 5,Virat,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:12:27,9,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
12,atif@uplora.live,Atif,RM,Pranil,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:10:05,10,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
13,ayushman@uplora.live,Ayushman,RM,Pranil,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:07:25,10,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
14,bikash@uplora.live,Bikash,P1,Sameer,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:24:24,10,9,0 days 00:37:10,0 days 00:40:52,7,0,0 days 00:00:00,0 days 00:00:00,0
15,deepak@uplora.live,Deepak,P4,KASIF,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:13:35,8,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
16,dhruv@uplora.live,Dhruv,RM,Pranil,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:03:31,3,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
17,harish@uplora.live,Harish,P4 - Dialer,KASIF,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:20:02,1,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
18,imran@uplora.live,Imran,P4 - Dialer,KASIF,4,0 days 00:00:00,0 days 00:01:55,2,0,0 days 00:00:00,...,0 days 00:37:16,4,13,0 days 00:06:23,0 days 00:12:13,5,0,0 days 00:00:00,0 days 00:00:00,0
19,irfan@uplora.live,Irfan,RM,Pranil,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:05:42,8,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
20,jaideep@uplora.live,Jaideep,RM,Virat,24,0 days 00:21:09,0 days 00:31:42,24,0,0 days 00:00:00,...,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
21,jaya@uplora.live,Jaya,P2,Armaan,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
22,junaid@uplora.live,Junaid,P1,Sameer,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:09:32,13,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
23,karishma@uplora.live,Karishma,P2,Armaan,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:01:57,3,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
24,kartik@uplora.live,Kartik,RM,Pranil,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:13:52,12,10,0 days 00:04:09,0 days 00:07:56,8,0,0 days 00:00:00,0 days 00:00:00,0
25,lakhan@uplora.live,Lakhan A,Pool 5,Virat,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
26,mayank@uplora.live,Mayank,P1,Sameer,1,0 days 00:00:00,0 days 00:00:13,1,0,0 days 00:00:00,...,0 days 00:11:27,6,1,0 days 00:01:09,0 days 00:01:09,1,0,0 days 00:00:00,0 days 00:00:00,0
27,mujeeb@uplora.live,Mujeeb,P4,KASIF,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:19:35,31,2,0 days 00:00:46,0 days 00:01:51,2,0,0 days 00:00:00,0 days 00:00:00,0
28,naman@uplora.live,Naman,P1,Sameer,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:09:54,15,5,0 days 00:00:18,0 days 00:02:28,5,1,0 days 00:00:35,0 days 00:00:54,1
29,nikita@uplora.live,Nikita,P2- Dialer,Armaan,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:23:44,11,12,0 days 00:03:21,0 days 00:08:22,5,0,0 days 00:00:00,0 days 00:00:00,0
30,nirvik@uplora.live,Nirvik,P1,Sameer,0,0 days 00:00:00,0 days 00:00:00,0,3,0 days 00:00:00,...,0 days 00:10:55,10,1,0 days 00:00:00,0 days 00:00:52,1,0,0 days 00:00:00,0 days 00:00:00,0
31,nishita@uplora.live,Nishita A,Pool 5,Virat,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
32,omkar@uplora.live,Omkar,P4 - Dialer,KASIF,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:10:46,5,2,0 days 00:00:00,0 days 00:00:17,1,0,0 days 00:00:00,0 days 00:00:00,0
33,prakash@uplora.live,Prakash,P2,Armaan,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:26:05,8,1,0 days 00:00:00,0 days 00:00:51,1,0,0 days 00:00:00,0 days 00:00:00,0
34,prashant@uplora.live,Prashant A,Pool 5,Virat,1,0 days 00:02:52,0 days 00:03:02,1,0,0 days 00:00:00,...,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
35,raghav@uplora.live,Raghav,P2,Armaan,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:00:02,2,2,0 days 00:01:25,0 days 00:02:10,2,0,0 days 00:00:00,0 days 00:00:00,0
36,rahmatullah@uplora.live,Rahmatullah,RM,Virat,3,0 days 00:01:12,0 days 00:02:16,3,0,0 days 00:00:00,...,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
37,reyansh@uplora.live,Reyansh,Dialer,KASIF,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
38,rizwana@uplora.live,Rizwana,P2- Dialer,Armaan,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
39,sabina@uplora.live,Sabina,RM,Pranil,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:14:57,7,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
40,samar@uplora.live,Samar,P1,Sameer,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:18:48,21,8,0 days 00:00:30,0 days 00:05:50,6,0,0 days 00:00:00,0 days 00:00:00,0
41,sandhya@uplora.live,Sandhya,P2- Dialer,Armaan,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:33:41,24,8,0 days 00:05:14,0 days 00:09:21,8,0,0 days 00:00:00,0 days 00:00:00,0
42,shaqib@uplora.live,Shaqib,P1,Sameer,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:14:12,14,10,0 days 00:18:27,0 days 00:18:27,9,1,0 days 00:03:16,0 days 00:03:16,1
43,sunita@uplora.live,Sunita,P4 - Dialer,KASIF,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:04:54,4,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
44,swati@uplora.live,Swati,P3,Armaan,0,0 days 00:00:00,0 days 00:00:00,0,12,0 days 00:00:11,...,0 days 00:17:50,5,17,0 days 00:08:32,0 days 00:19:15,12,0,0 days 00:00:00,0 days 00:00:00,0
45,upasana@uplora.live,Upasana,P2,Armaan,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0
46,vidhya@uplora.live,Vidhya A,Pool 5,Virat,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days 00:12:13,10,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,0 days 00:00:00,0

In [122]:
duration_cols = [col for col in df_reordered.columns if col.endswith("Duration")]
tim_cols = [col for col in df_reordered.columns if col.endswith("Talk Time")]
for col in duration_cols:
    df_reordered[col] = df_reordered[col].astype(str).str.replace("0 days ", "", regex=False)
for col in tim_cols:
    df_reordered[col] = df_reordered[col].astype(str).str.replace("0 days ", "", regex=False)
df_reordered

,CRM ID,Full Name,Pool,TL,0 to 8 AM - Calls,0 to 8 AM - Talk Time,0 to 8 AM - Total Call Duration,0 to 8 AM - Unique Calls,8 to 9 AM - Calls,8 to 9 AM - Talk Time,...,18 to 19 PM - Total Call Duration,18 to 19 PM - Unique Calls,19 to 20 PM - Calls,19 to 20 PM - Talk Time,19 to 20 PM - Total Call Duration,19 to 20 PM - Unique Calls,20+ - Calls,20+ - Talk Time,20+ - Total Call Duration,20+ - Unique Calls
0,aayush@uplora.live,Aayush,Dialer,KASIF,7,00:03:37,00:08:34,7,0,00:00:00,...,00:00:00,0,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
1,abdul@uplora.live,Abdul,P1,Sameer,5,00:01:17,00:04:44,2,0,00:00:00,...,00:00:00,0,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
2,abhishek@uplora.live,Abhishek A,Pool 5,Virat,5,00:00:45,00:02:48,5,0,00:00:00,...,00:00:00,0,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
3,abiral@uplora.live,Abiral,P4,KASIF,0,00:00:00,00:00:00,0,0,00:00:00,...,00:12:59,4,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
4,advik@uplora.live,Advik,Dialer,KASIF,0,00:00:00,00:00:00,0,0,00:00:00,...,00:00:00,0,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
5,aelina@uplora.live,Aelina,Dialer,KASIF,2,00:07:05,00:08:13,2,0,00:00:00,...,00:00:00,0,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
6,ajit@uplora.live,Ajit,P2- Dialer,Armaan,0,00:00:00,00:00:00,0,0,00:00:00,...,00:10:39,3,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
7,akhil@uplora.live,Akhil,P4 - Dialer,KASIF,0,00:00:00,00:00:00,0,0,00:00:00,...,00:00:00,0,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
8,akshay@uplora.live,Akshay A,Pool 5,Virat,2,00:00:39,00:01:08,2,0,00:00:00,...,00:22:10,9,1,00:00:00,00:00:16,1,0,00:00:00,00:00:00,0
9,anita@uplora.live,Anita,P1,Sameer,3,00:01:59,00:03:14,1,0,00:00:00,...,00:00:00,0,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
10,ankit@uplora.live,Ankit,RM,Virat,0,00:00:00,00:00:00,0,0,00:00:00,...,00:16:02,1,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
11,anushka@uplora.live,Anushka A,Pool 5,Virat,0,00:00:00,00:00:00,0,0,00:00:00,...,00:12:27,9,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
12,atif@uplora.live,Atif,RM,Pranil,0,00:00:00,00:00:00,0,0,00:00:00,...,00:10:05,10,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
13,ayushman@uplora.live,Ayushman,RM,Pranil,0,00:00:00,00:00:00,0,0,00:00:00,...,00:07:25,10,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
14,bikash@uplora.live,Bikash,P1,Sameer,0,00:00:00,00:00:00,0,0,00:00:00,...,00:24:24,10,9,00:37:10,00:40:52,7,0,00:00:00,00:00:00,0
15,deepak@uplora.live,Deepak,P4,KASIF,0,00:00:00,00:00:00,0,0,00:00:00,...,00:13:35,8,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
16,dhruv@uplora.live,Dhruv,RM,Pranil,0,00:00:00,00:00:00,0,0,00:00:00,...,00:03:31,3,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
17,harish@uplora.live,Harish,P4 - Dialer,KASIF,0,00:00:00,00:00:00,0,0,00:00:00,...,00:20:02,1,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
18,imran@uplora.live,Imran,P4 - Dialer,KASIF,4,00:00:00,00:01:55,2,0,00:00:00,...,00:37:16,4,13,00:06:23,00:12:13,5,0,00:00:00,00:00:00,0
19,irfan@uplora.live,Irfan,RM,Pranil,0,00:00:00,00:00:00,0,0,00:00:00,...,00:05:42,8,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
20,jaideep@uplora.live,Jaideep,RM,Virat,24,00:21:09,00:31:42,24,0,00:00:00,...,00:00:00,0,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
21,jaya@uplora.live,Jaya,P2,Armaan,0,00:00:00,00:00:00,0,0,00:00:00,...,00:00:00,0,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
22,junaid@uplora.live,Junaid,P1,Sameer,0,00:00:00,00:00:00,0,0,00:00:00,...,00:09:32,13,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
23,karishma@uplora.live,Karishma,P2,Armaan,0,00:00:00,00:00:00,0,0,00:00:00,...,00:01:57,3,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
24,kartik@uplora.live,Kartik,RM,Pranil,0,00:00:00,00:00:00,0,0,00:00:00,...,00:13:52,12,10,00:04:09,00:07:56,8,0,00:00:00,00:00:00,0
25,lakhan@uplora.live,Lakhan A,Pool 5,Virat,0,00:00:00,00:00:00,0,0,00:00:00,...,00:00:00,0,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
26,mayank@uplora.live,Mayank,P1,Sameer,1,00:00:00,00:00:13,1,0,00:00:00,...,00:11:27,6,1,00:01:09,00:01:09,1,0,00:00:00,00:00:00,0
27,mujeeb@uplora.live,Mujeeb,P4,KASIF,0,00:00:00,00:00:00,0,0,00:00:00,...,00:19:35,31,2,00:00:46,00:01:51,2,0,00:00:00,00:00:00,0
28,naman@uplora.live,Naman,P1,Sameer,0,00:00:00,00:00:00,0,0,00:00:00,...,00:09:54,15,5,00:00:18,00:02:28,5,1,00:00:35,00:00:54,1
29,nikita@uplora.live,Nikita,P2- Dialer,Armaan,0,00:00:00,00:00:00,0,0,00:00:00,...,00:23:44,11,12,00:03:21,00:08:22,5,0,00:00:00,00:00:00,0
30,nirvik@uplora.live,Nirvik,P1,Sameer,0,00:00:00,00:00:00,0,3,00:00:00,...,00:10:55,10,1,00:00:00,00:00:52,1,0,00:00:00,00:00:00,0
31,nishita@uplora.live,Nishita A,Pool 5,Virat,0,00:00:00,00:00:00,0,0,00:00:00,...,00:00:00,0,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
32,omkar@uplora.live,Omkar,P4 - Dialer,KASIF,0,00:00:00,00:00:00,0,0,00:00:00,...,00:10:46,5,2,00:00:00,00:00:17,1,0,00:00:00,00:00:00,0
33,prakash@uplora.live,Prakash,P2,Armaan,0,00:00:00,00:00:00,0,0,00:00:00,...,00:26:05,8,1,00:00:00,00:00:51,1,0,00:00:00,00:00:00,0
34,prashant@uplora.live,Prashant A,Pool 5,Virat,1,00:02:52,00:03:02,1,0,00:00:00,...,00:00:00,0,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
35,raghav@uplora.live,Raghav,P2,Armaan,0,00:00:00,00:00:00,0,0,00:00:00,...,00:00:02,2,2,00:01:25,00:02:10,2,0,00:00:00,00:00:00,0
36,rahmatullah@uplora.live,Rahmatullah,RM,Virat,3,00:01:12,00:02:16,3,0,00:00:00,...,00:00:00,0,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
37,reyansh@uplora.live,Reyansh,Dialer,KASIF,0,00:00:00,00:00:00,0,0,00:00:00,...,00:00:00,0,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
38,rizwana@uplora.live,Rizwana,P2- Dialer,Armaan,0,00:00:00,00:00:00,0,0,00:00:00,...,00:00:00,0,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
39,sabina@uplora.live,Sabina,RM,Pranil,0,00:00:00,00:00:00,0,0,00:00:00,...,00:14:57,7,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
40,samar@uplora.live,Samar,P1,Sameer,0,00:00:00,00:00:00,0,0,00:00:00,...,00:18:48,21,8,00:00:30,00:05:50,6,0,00:00:00,00:00:00,0
41,sandhya@uplora.live,Sandhya,P2- Dialer,Armaan,0,00:00:00,00:00:00,0,0,00:00:00,...,00:33:41,24,8,00:05:14,00:09:21,8,0,00:00:00,00:00:00,0
42,shaqib@uplora.live,Shaqib,P1,Sameer,0,00:00:00,00:00:00,0,0,00:00:00,...,00:14:12,14,10,00:18:27,00:18:27,9,1,00:03:16,00:03:16,1
43,sunita@uplora.live,Sunita,P4 - Dialer,KASIF,0,00:00:00,00:00:00,0,0,00:00:00,...,00:04:54,4,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
44,swati@uplora.live,Swati,P3,Armaan,0,00:00:00,00:00:00,0,12,00:00:11,...,00:17:50,5,17,00:08:32,00:19:15,12,0,00:00:00,00:00:00,0
45,upasana@uplora.live,Upasana,P2,Armaan,0,00:00:00,00:00:00,0,0,00:00:00,...,00:00:00,0,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0
46,vidhya@uplora.live,Vidhya A,Pool 5,Virat,0,00:00:00,00:00:00,0,0,00:00:00,...,00:12:13,10,0,00:00:00,00:00:00,0,0,00:00:00,00:00:00,0

In [123]:

# 1. Identify columns dynamically
call_cols = [col for col in df_reordered.columns if col.endswith("- Calls")]
talk_time_cols = [col for col in df_reordered.columns if col.endswith("Talk Time")]
duration_cols = [col for col in df_reordered.columns if col.endswith("Total Call Duration")]

# 2. Convert HH:MM:SS to timedelta
for col in talk_time_cols + duration_cols:
    df_reordered[col] = pd.to_timedelta(df_reordered[col])

# 3. Compute totals
df_reordered["Total Calls"] = df_reordered[call_cols].sum(axis=1)
df_reordered["Total Talk Time"] = df_reordered[talk_time_cols].sum(axis=1)
df_reordered["Total Call Duration"] = df_reordered[duration_cols].sum(axis=1)

In [124]:
df_reordered.head()

,CRM ID,Full Name,Pool,TL,0 to 8 AM - Calls,0 to 8 AM - Talk Time,0 to 8 AM - Total Call Duration,0 to 8 AM - Unique Calls,8 to 9 AM - Calls,8 to 9 AM - Talk Time,...,19 to 20 PM - Talk Time,19 to 20 PM - Total Call Duration,19 to 20 PM - Unique Calls,20+ - Calls,20+ - Talk Time,20+ - Total Call Duration,20+ - Unique Calls,Total Calls,Total Talk Time,Total Call Duration
0,aayush@uplora.live,Aayush,Dialer,KASIF,7,0 days 00:03:37,0 days 00:08:34,7,0,0 days,...,0 days,0 days,0,0,0 days,0 days,0,9,0 days 00:04:46,0 days 00:09:43
1,abdul@uplora.live,Abdul,P1,Sameer,5,0 days 00:01:17,0 days 00:04:44,2,0,0 days,...,0 days,0 days,0,0,0 days,0 days,0,6,0 days 00:11:17,0 days 00:14:44
2,abhishek@uplora.live,Abhishek A,Pool 5,Virat,5,0 days 00:00:45,0 days 00:02:48,5,0,0 days,...,0 days,0 days,0,0,0 days,0 days,0,5,0 days 00:00:45,0 days 00:02:48
3,abiral@uplora.live,Abiral,P4,KASIF,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days,...,0 days,0 days,0,0,0 days,0 days,0,151,0 days 01:45:47,0 days 02:48:19
4,advik@uplora.live,Advik,Dialer,KASIF,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days,...,0 days,0 days,0,0,0 days,0 days,0,12,0 days 00:09:16,0 days 00:09:16

In [125]:
formatted_df

,Date,Pool,TL,CRM ID,Employee Code,Full Name,Vertical,Total_Dialed_Calls,Unique_Dialed_Numbers,Total_Connected_Calls,...,Total_Call_GT_30,Total_Duration,Total_Talk_Time,Total_Talk_Time_GT_30,Total_Connected_Hold_Time,Total_Gap_Duration,Avg_Gap_per_call,Gap Duration After Leverage,Login Hours,Attendance
0,2026-03-31,NaN,NaN,0,NaN,NaN,NaN,0,0,0,...,0,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,Absent
2,2026-03-31,Dialer,KASIF,aayush@uplora.live,U-1124,Aayush,MarketBhai,2,1,0,...,0,00:01:09,00:00:00,00:00:00,00:00:00,00:00:57,00:00:28,00:00:00,01:02:06,Absent
4,2026-03-31,P1,Sameer,abdul@uplora.live,E-1236,Abdul,MarketBhai,1,1,1,...,1,00:10:00,00:10:00,00:10:00,00:00:00,00:00:00,00:00:00,00:00:00,01:10:00,Absent
6,2026-03-31,Pool 5,Virat,abhishek@uplora.live,NaN,Abhishek A,MarketBhai,0,0,0,...,0,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,Absent
8,2026-03-31,P4,KASIF,abiral@uplora.live,U-1145,Abiral,MarketBhai,0,0,0,...,0,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,Absent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,2026-04-01,P3,Armaan,swati@uplora.live,U-1098,Swati,MarketBhai,177,78,56,...,27,02:30:13,01:01:58,00:54:22,00:00:00,07:48:26,00:02:39,05:35:41,11:18:39,Present
127,2026-04-01,P2,Armaan,upasana@uplora.live,U-1021,Upasana,MarketBhai,0,0,0,...,0,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,Absent
129,2026-04-01,Pool 5,Virat,vidhya@uplora.live,NaN,Vidhya A,MarketBhai,124,59,59,...,38,01:52:52,01:16:33,01:11:11,00:00:00,03:55:23,00:01:54,02:22:23,06:48:15,Warning
131,2026-04-01,P4,KASIF,yug@uplora.live,U-1134,Yug,MarketBhai,0,0,0,...,0,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,Absent
132,NaT,Pool 5,Virat,NaN,NaN,Aarzoo,MarketBhai,0,0,0,...,0,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,NaN,NaN

In [126]:
formatted_df.columns

Index(['Date', 'Pool', 'TL', 'CRM ID', 'Employee Code', 'Full Name',
       'Vertical', 'Total_Dialed_Calls', 'Unique_Dialed_Numbers',
       'Total_Connected_Calls', 'Total_Number_of_Call_Gap', 'Total_Call_GT_30',
       'Total_Duration', 'Total_Talk_Time', 'Total_Talk_Time_GT_30',
       'Total_Connected_Hold_Time', 'Total_Gap_Duration', 'Avg_Gap_per_call',
       'Gap Duration After Leverage', 'Login Hours', 'Attendance'],
      dtype='object')

In [127]:
df_reordered = pd.merge(df_reordered, formatted_df[['CRM ID', 'Unique_Dialed_Numbers', 'Total_Connected_Calls', 'Total_Call_GT_30', 'Total_Talk_Time_GT_30']], on='CRM ID', how='left')
df_reordered

,CRM ID,Full Name,Pool,TL,0 to 8 AM - Calls,0 to 8 AM - Talk Time,0 to 8 AM - Total Call Duration,0 to 8 AM - Unique Calls,8 to 9 AM - Calls,8 to 9 AM - Talk Time,...,20+ - Talk Time,20+ - Total Call Duration,20+ - Unique Calls,Total Calls,Total Talk Time,Total Call Duration,Unique_Dialed_Numbers,Total_Connected_Calls,Total_Call_GT_30,Total_Talk_Time_GT_30
0,aayush@uplora.live,Aayush,Dialer,KASIF,7,0 days 00:03:37,0 days 00:08:34,7,0,0 days 00:00:00,...,0 days,0 days,0,9,0 days 00:04:46,0 days 00:09:43,1,0,0,00:00:00
1,aayush@uplora.live,Aayush,Dialer,KASIF,7,0 days 00:03:37,0 days 00:08:34,7,0,0 days 00:00:00,...,0 days,0 days,0,9,0 days 00:04:46,0 days 00:09:43,7,2,1,00:03:27
2,abdul@uplora.live,Abdul,P1,Sameer,5,0 days 00:01:17,0 days 00:04:44,2,0,0 days 00:00:00,...,0 days,0 days,0,6,0 days 00:11:17,0 days 00:14:44,1,1,1,00:10:00
3,abdul@uplora.live,Abdul,P1,Sameer,5,0 days 00:01:17,0 days 00:04:44,2,0,0 days 00:00:00,...,0 days,0 days,0,6,0 days 00:11:17,0 days 00:14:44,2,1,1,00:01:17
4,abhishek@uplora.live,Abhishek A,Pool 5,Virat,5,0 days 00:00:45,0 days 00:02:48,5,0,0 days 00:00:00,...,0 days,0 days,0,5,0 days 00:00:45,0 days 00:02:48,0,0,0,00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,swati@uplora.live,Swati,P3,Armaan,0,0 days 00:00:00,0 days 00:00:00,0,12,0 days 00:00:11,...,0 days,0 days,0,177,0 days 01:01:58,0 days 02:30:13,78,56,27,00:54:22
90,upasana@uplora.live,Upasana,P2,Armaan,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days,0 days,0,10,0 days 00:05:26,0 days 00:05:26,5,5,1,00:01:24
91,upasana@uplora.live,Upasana,P2,Armaan,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days,0 days,0,10,0 days 00:05:26,0 days 00:05:26,0,0,0,00:00:00
92,vidhya@uplora.live,Vidhya A,Pool 5,Virat,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days,0 days,0,124,0 days 01:16:33,0 days 01:52:52,0,0,0,00:00:00
93,vidhya@uplora.live,Vidhya A,Pool 5,Virat,0,0 days 00:00:00,0 days 00:00:00,0,0,0 days 00:00:00,...,0 days,0 days,0,124,0 days 01:16:33,0 days 01:52:52,59,59,38,01:11:11

In [128]:
df_reordered["Total Calls"] = df_reordered["Total Calls"].astype(int)
df_reordered["Total Talk Time"] = df_reordered["Total Talk Time"].dt.components.apply(
    lambda x: f"{int(x.hours + x.days*24):02d}:{int(x.minutes):02d}:{int(x.seconds):02d}",
    axis=1
)
df_reordered["Total Call Duration"] = df_reordered["Total Call Duration"].dt.components.apply(
    lambda x: f"{int(x.hours + x.days*24):02d}:{int(x.minutes):02d}:{int(x.seconds):02d}",
    axis=1)

### Export

In [129]:
save_path = r'C:\Users\Akhil\Downloads'

df_reordered.to_csv(f'{save_path}\\Cre_Summary_1_04.csv', index=False)
formatted_df.to_csv(f'{save_path}\\Summary_1_04.csv', index=False)
D.to_csv(f'{save_path}\\Dialer_1_04.csv', index=False)
crm_id_null_df.to_csv(f'{save_path}\\Not_Found_Users_1_04.csv', index=False)